## What `GameDataRegistry.atlas_for()` hands back: one visual ID resolved to
## either a real baked atlas or a procedural placeholder (PLAN.md 2.1, 6.1).
## Phase 0.2a.
##
## The whole point of the seam is that callers do not branch on which one they
## got for *positioning* -- both answer frame_at() with a rect and an anchor in
## the same coordinate convention. They do branch when drawing, because one
## blits a texture region and the other draws shapes, and that is the only place
## `is_placeholder` should be read.
##
## Atlas format is PLAN.md 9.1, generated by isobake. This class never writes it
## and never merges into it: a rebake rewrites the file wholesale.
class_name AtlasEntry
extends RefCounted

## Canonical facing order, and the order `directions.table` is always stored in.
## isobake emits all 8 entries regardless of how many it *stored*, each resolved
## to a stored frame plus a flip, so the view layer reads the convention instead
## of re-deriving mirroring per asset (PLAN.md 9.1).
const FACINGS := ["S", "SW", "W", "NW", "N", "NE", "E", "SE"]

const STATIC_ANIM := &"static"

## The open-gate pose (PLAN.md 5.8, art delivered 2026-08-28). Named here beside
## `STATIC_ANIM` because those two are the whole clip vocabulary a BUILDING has --
## a unit's clip names come off the sim's task instead.
##
## **`static` IS THE CLOSED POSE, deliberately, and that is the art side's design.**
## A gate at rest is shut, so an atlas that never got an `open` clip draws exactly
## what it drew before this existed, and `resolve_anim` falls back for it without
## anybody wiring a special case. Only two clips were baked of the four 0 A.D.
## ships: `opening`/`closing` are ~12 frames each at 8 directions, about fourteen
## extra pages per gate for half a second of swing.
const OPEN_ANIM := &"open"

## Clip -> the clip that MEANS THE SAME THING to an atlas that lacks it, tried before
## the generic fallbacks below. Both entries are the 2026-08-28 wildlife delivery, and
## both exist because one species got a clip its five siblings did not:
##
##   `run`     the deer bolts, and only the deer was given a run. Without this a
##             fleeing sheep resolves to `idle` -- STANDING STILL WHILE SLIDING across
##             the map at flee speed, which is worse than the walk it played before
##             anything asked for a run.
##   `feeding` only the cattle has one; 0 A.D.'s boar and deer look like they declare
##             it and the name is a variant with no animation behind it.
##
## Note both fall back to a clip every animal HAS, which is the whole test for whether
## an alias belongs here: it is a rewording of a request, not a second guess at it. A
## clip with no such synonym stays out and takes the generic chain.
const _ANIM_ALIAS := {
	&"run": &"walk",
	&"feeding": &"idle",
}

var id: StringName = &""
var is_placeholder := true

## What to multiply the drawn frame by, from the visuals.json entry's `scale` (13.2b).
## 1.0 for everything but `vis.dragon_baby`, which is `vis.dragon_rigged` at 0.2.
##
## SET BY THE RESOLVER, NOT BY THE ATLAS. It belongs to the visual ENTRY and not to the
## baked file -- that is what lets two entries share one atlas and draw at two sizes,
## which is the whole point of it and the reason a second 7.7 MB bake was not needed.
## `GameDataRegistry._resolve` writes it, and the resolved-entry cache is keyed per
## visual id (`_skin_key`), so the two entries are two objects and cannot tread on each
## other despite parsing the same file.
##
## THE SPRITE ONLY. Anything measured in metres -- the selection ring, the health dot,
## the placeholder box -- comes off `placeholder.footprint_m` / `height_m`, which are
## authored at the scaled size. visuals.json's `_note_dragon_baby` has the argument.
var scale: float = 1.0

# ── placeholder branch ─────────────────────────────────────────────────────
var placeholder: PlaceholderSpec = null

# ── atlas branch ───────────────────────────────────────────────────────────
## Absolute res:// paths to the atlas PNG pages, indexed by a frame's `page`.
var pages: PackedStringArray = PackedStringArray()
var pixels_per_metre := Iso.PIXELS_PER_METRE
## Parsed `frames`, in atlas order. Each: {page:int, rect:Rect2i, anchor:Vector2}
var frames: Array[Dictionary] = []
## anim name -> {fps:float, loop:bool, frames:int, first:int}
var anims: Dictionary = {}
## 8 entries in FACINGS order. Each: {stored_index:int, flip_x:bool}
##
## **READ EXACTLY AS THE FILE STATES IT, and there is now a decision behind that.**
## A half-turn compensation lived here for one day (2026-08-22): the zeroad adapter
## bakes a subject 180 degrees from the direction the atlas labels it, 81 of 171
## recipes cancel that with `yaw_offset_deg = 180.0`, and the rest -- every unit,
## ship, animal and siege engine -- do not. Flagging those atlases in visuals.json
## and rotating the request here fixed idle and walk and **did not fix attacking**,
## which is where the project owner had reported it in the first place. The owner's
## call, and it is the right one: the defect is in the recipes, the fix belongs in
## the bake, and a compensation that has to be un-applied in step with a delivery
## is not worth carrying for a partial result. See PLAN.md 13.2 item 10.
var dir_table: Array[Dictionary] = []

var _textures: Array[Texture2D] = []


static func from_placeholder(p_id: StringName, spec: PlaceholderSpec) -> AtlasEntry:
	var e := AtlasEntry.new()
	e.id = p_id
	e.is_placeholder = true
	e.placeholder = spec
	return e


## `dir` is the directory the atlas JSON was loaded from, since `pages` inside the
## file are bare filenames written beside it by isobake.
static func from_atlas_dict(p_id: StringName, d: Dictionary, dir: String) -> AtlasEntry:
	var e := AtlasEntry.new()
	e.id = p_id
	e.is_placeholder = false
	e.pixels_per_metre = float(d.get("pixels_per_metre", Iso.PIXELS_PER_METRE))

	for page in d.get("pages", []):
		e.pages.append(dir.path_join(str(page)))

	for f in d.get("frames", []):
		var rect: Array = f.get("rect", [0, 0, 0, 0])
		var anchor: Array = f.get("anchor", [0.0, 0.0])
		e.frames.append({
			"page": int(f.get("page", 0)),
			"rect": Rect2i(int(rect[0]), int(rect[1]), int(rect[2]), int(rect[3])),
			"anchor": Vector2(float(anchor[0]), float(anchor[1])),
		})

	for name in d.get("anims", {}):
		var a: Dictionary = d["anims"][name]
		e.anims[StringName(name)] = {
			"fps": float(a.get("fps", 1.0)),
			"loop": bool(a.get("loop", false)),
			"frames": int(a.get("frames", 1)),
			"first": int(a.get("first", 0)),
		}

	var table: Array = d.get("directions", {}).get("table", [])
	for entry in table:
		e.dir_table.append({
			"stored_index": int(entry.get("stored_index", 0)),
			"flip_x": bool(entry.get("flip_x", false)),
		})

	e._textures.resize(e.pages.size())
	return e


# ── queries ────────────────────────────────────────────────────────────────

func has_anim(name: StringName) -> bool:
	return anims.has(name)


## The anim to actually play for a requested one. A static prop has only
## `static`, and a partly-baked unit may be missing `work_hunt` while having
## `idle`; in both cases falling back beats drawing nothing (PLAN.md 2.1 --
## gameplay never blocks on art).
func resolve_anim(name: StringName) -> StringName:
	if is_placeholder:
		return name
	if anims.has(name):
		return name
	# A synonym the atlas does have, before the generic fallbacks: a running animal
	# with no `run` should walk, not stand. See `_ANIM_ALIAS`.
	var alias: StringName = _ANIM_ALIAS.get(name, &"")
	if not alias.is_empty() and anims.has(alias):
		return alias
	if anims.has(STATIC_ANIM):
		return STATIC_ANIM
	if anims.has(&"idle"):
		return &"idle"
	return anims.keys()[0] if not anims.is_empty() else name


func frame_count(name: StringName) -> int:
	if is_placeholder:
		return 1
	var a: Dictionary = anims.get(resolve_anim(name), {})
	return int(a.get("frames", 1))


func fps(name: StringName) -> float:
	if is_placeholder:
		return 1.0
	return float(anims.get(resolve_anim(name), {}).get("fps", 1.0))


func loops(name: StringName) -> bool:
	if is_placeholder:
		return false
	return bool(anims.get(resolve_anim(name), {}).get("loop", false))


## Resolve (anim, facing, frame) to something drawable, or {} for a placeholder /
## an out-of-range request.
##
## The index formula is PLAN.md 9.1: within an anim, frames are direction-major --
## `first + stored_direction * frames + frame`.
func frame_at(name: StringName, facing: int, frame: int) -> Dictionary:
	if is_placeholder or dir_table.is_empty():
		return {}

	var a: Dictionary = anims.get(resolve_anim(name), {})
	if a.is_empty():
		return {}

	var dir: Dictionary = dir_table[posmod(facing, dir_table.size())]
	var count := int(a["frames"])
	var index := int(a["first"]) + int(dir["stored_index"]) * count + posmod(frame, count)
	if index < 0 or index >= frames.size():
		return {}

	var f: Dictionary = frames[index]
	return {
		"page": int(f["page"]),
		"rect": f["rect"] as Rect2i,
		"anchor": f["anchor"] as Vector2,
		"flip_x": bool(dir["flip_x"]),
	}


## Lazily loaded so that parsing an atlas -- and therefore the whole seam and its
## tests -- never depends on the PNG pages being present or on a rendering
## context existing.
func texture(page: int) -> Texture2D:
	if page < 0 or page >= pages.size():
		return null
	if _textures[page] == null:
		_textures[page] = page_texture(pages[page])
	return _textures[page]


## ⛔ **A PAGE IS DECODED FROM ITS PNG AND IS NEVER A `load()`, AND THAT IS THE ART PACK'S
## DOING.** This was `if ResourceLoader.exists(p): load(p)` until 2026-09-12.
##
## `art_base_v1.zip` is a plain zip mounted with `ProjectSettings.load_resource_pack()`
## -- a `.pck` is Godot's own container and a zip is what the owner asked for, and the engine
## takes either. **The files inside it are NOT imported resources.** There is no `.import`
## sidecar and no `.godot/imported/*.ctex`, because nothing in Godot ever saw them: they were
## zipped by `tools/build_packs.py`, in Python, off the staged tree.
##
## Measured on 4.7.1 against a real mounted zip, all four in one run:
##
##   | `load_resource_pack()` on a zip   | **true** -- it mounts |
##   | `FileAccess` / `DirAccess`        | see the files         |
##   | `Image` decode from the bytes     | 64x64 RGBA8, fine     |
##   | `ResourceLoader.exists` / `load()`| **false**, and `load()` pushes an engine error |
##
## So the old line returned `null` for every pack-delivered page. ⚠️ **AND THE FAILURE WOULD
## NOT HAVE BEEN THE MAGENTA PLACEHOLDER**, which is the thing that makes it worth this many
## lines: the placeholder branch is chosen in `GameDataRegistry._resolve` by whether the
## `.atlas.json` PARSED, and the JSON parses perfectly -- `FileAccess` reads it out of the zip.
## Every unit in the game would have drawn *nothing at all*, with no warning anywhere.
##
## ⚠️ **THE RAW ROUTE IS THE ONLY ROUTE ON PURPOSE, INCLUDING IN THE EDITOR.** Keeping
## `ResourceLoader` as a first attempt would work here -- the staged tree IS imported on this
## workstation -- and that is exactly the objection: the editor would take the imported path,
## the phone would take the zip path, and **nothing anybody runs before shipping would ever
## execute what ships.** One path, and a red suite is the report. §5's rule about a check that
## cannot see the fault it is for, applied to a code path instead of a test.
##
## Costs nothing measurable: the atlases import at the default 2D settings -- lossless, no
## mipmaps -- so a `CompressedTexture2D` was already RGBA8 in VRAM by the time it drew.
static func page_texture(path: String) -> Texture2D:
	if path.is_empty():
		return null
	if _page_cache.has(path):
		return _page_cache[path]
	# Asked before loading rather than after: a missing path is an engine error from either
	# loader, and a clean checkout has no atlases at all -- a normal state (`_load_atlas`'s
	# rule) that must not fill the log.
	if not FileAccess.file_exists(path):
		return null

	# ⛔ **THE BYTES ARE READ AND DECODED, RATHER THAN `Image.load_from_file(path)`.** That
	# call was the first version and it is wrong here in a way that only shows on a
	# workstation, which is the worst place for a difference to live.
	#
	# `Image::load()` warns *"Loaded resource as image file, this will not work on export"*
	# whenever `ResourceLoader::exists()` is true of the path -- i.e. whenever an `.import`
	# sidecar is beside it. On a machine with the staged tree that is EVERY atlas page: 170
	# warnings a run, each one naming a real hazard that does not apply, burying anything
	# that does. On a device it never fires, because a zip member has no sidecar.
	#
	# So the two environments would have disagreed about the log while agreeing about the
	# pixels. `FileAccess` + a buffer decode has no such heuristic: it reads the same bytes
	# from a staged file and from a mounted zip and says nothing about either.
	var bytes := FileAccess.get_file_as_bytes(path)
	if bytes.is_empty():
		push_warning("AtlasEntry: '%s' is empty or unreadable" % path)
		return null
	var img := Image.new()
	var err := _decode(img, path.get_extension().to_lower(), bytes)
	if err != OK:
		push_warning("AtlasEntry: '%s' did not decode (error %d)" % [path, err])
		return null
	var tex := ImageTexture.create_from_image(img)
	_page_cache[path] = tex
	return tex


## Decode by EXTENSION, from a table, because the buffer loaders are one per format and
## there is no sniffing helper. isobake writes PNG and has always written PNG -- the other
## two rows are here so that changing that is one line rather than a fault that presents as
## every sprite in the game vanishing at once.
static func _decode(img: Image, extension: String, bytes: PackedByteArray) -> int:
	match extension:
		"png":
			return img.load_png_from_buffer(bytes)
		"webp":
			return img.load_webp_from_buffer(bytes)
		"jpg", "jpeg":
			return img.load_jpg_from_buffer(bytes)
		_:
			return ERR_FILE_UNRECOGNIZED


## Page path -> texture, for the whole process.
##
## **This replaces a dedupe that came free and is now ours to do.** `load()` went through
## Godot's resource cache, so two entries naming one page shared one texture -- which is not
## a curiosity here: `vis.dragon_baby` and `vis.dragon_rigged` are the same atlas at two
## scales (13.2b), and every `variants` list is several ids over shared art. Decoding a 7.7 MB
## page twice is the cost of leaving this out, and nothing would report it.
##
## Held for the life of the process, which is the lifetime the old code already had:
## `GameDataRegistry._resolved` never drops an entry and `_textures` never drops a page.
static var _page_cache: Dictionary = {}


## Drop every decoded page. Called when an art pack is mounted mid-session
## (`GameDataRegistry.load_all(true)`), because a page cached from the placeholder-era path
## would otherwise outlive the art arriving.
static func forget_pages() -> void:
	_page_cache.clear()
