## What `GameDataRegistry.atlas_for()` hands back: one visual ID resolved to
## either a real baked atlas or a procedural placeholder (PLAN.md 2.1, 6.1).
## Phase 0.2a.
##
## The whole point of the seam is that callers do not branch on which one they
## got for *positioning* -- both answer frame_at() with a rect and an anchor in
## the same coordinate convention. They do branch when drawing, because one
## blits a texture region and the other draws shapes, and that is the only place
## `is_placeholder` should be read.
##
## Atlas format is PLAN.md 9.1, generated by isobake. This class never writes it
## and never merges into it: a rebake rewrites the file wholesale.
class_name AtlasEntry
extends RefCounted

## Canonical facing order, and the order `directions.table` is always stored in.
## isobake emits all 8 entries regardless of how many it *stored*, each resolved
## to a stored frame plus a flip, so the view layer reads the convention instead
## of re-deriving mirroring per asset (PLAN.md 9.1).
const FACINGS := ["S", "SW", "W", "NW", "N", "NE", "E", "SE"]

const STATIC_ANIM := &"static"

var id: StringName = &""
var is_placeholder := true

# ── placeholder branch ─────────────────────────────────────────────────────
var placeholder: PlaceholderSpec = null

# ── atlas branch ───────────────────────────────────────────────────────────
## Absolute res:// paths to the atlas PNG pages, indexed by a frame's `page`.
var pages: PackedStringArray = PackedStringArray()
var pixels_per_metre := Iso.PIXELS_PER_METRE
## Parsed `frames`, in atlas order. Each: {page:int, rect:Rect2i, anchor:Vector2}
var frames: Array[Dictionary] = []
## anim name -> {fps:float, loop:bool, frames:int, first:int}
var anims: Dictionary = {}
## 8 entries in FACINGS order. Each: {stored_index:int, flip_x:bool}
var dir_table: Array[Dictionary] = []

var _textures: Array[Texture2D] = []


static func from_placeholder(p_id: StringName, spec: PlaceholderSpec) -> AtlasEntry:
	var e := AtlasEntry.new()
	e.id = p_id
	e.is_placeholder = true
	e.placeholder = spec
	return e


## `dir` is the directory the atlas JSON was loaded from, since `pages` inside the
## file are bare filenames written beside it by isobake.
static func from_atlas_dict(p_id: StringName, d: Dictionary, dir: String) -> AtlasEntry:
	var e := AtlasEntry.new()
	e.id = p_id
	e.is_placeholder = false
	e.pixels_per_metre = float(d.get("pixels_per_metre", Iso.PIXELS_PER_METRE))

	for page in d.get("pages", []):
		e.pages.append(dir.path_join(str(page)))

	for f in d.get("frames", []):
		var rect: Array = f.get("rect", [0, 0, 0, 0])
		var anchor: Array = f.get("anchor", [0.0, 0.0])
		e.frames.append({
			"page": int(f.get("page", 0)),
			"rect": Rect2i(int(rect[0]), int(rect[1]), int(rect[2]), int(rect[3])),
			"anchor": Vector2(float(anchor[0]), float(anchor[1])),
		})

	for name in d.get("anims", {}):
		var a: Dictionary = d["anims"][name]
		e.anims[StringName(name)] = {
			"fps": float(a.get("fps", 1.0)),
			"loop": bool(a.get("loop", false)),
			"frames": int(a.get("frames", 1)),
			"first": int(a.get("first", 0)),
		}

	var table: Array = d.get("directions", {}).get("table", [])
	for entry in table:
		e.dir_table.append({
			"stored_index": int(entry.get("stored_index", 0)),
			"flip_x": bool(entry.get("flip_x", false)),
		})

	e._textures.resize(e.pages.size())
	return e


# ── queries ────────────────────────────────────────────────────────────────

func has_anim(name: StringName) -> bool:
	return anims.has(name)


## The anim to actually play for a requested one. A static prop has only
## `static`, and a partly-baked unit may be missing `work_hunt` while having
## `idle`; in both cases falling back beats drawing nothing (PLAN.md 2.1 --
## gameplay never blocks on art).
func resolve_anim(name: StringName) -> StringName:
	if is_placeholder:
		return name
	if anims.has(name):
		return name
	if anims.has(STATIC_ANIM):
		return STATIC_ANIM
	if anims.has(&"idle"):
		return &"idle"
	return anims.keys()[0] if not anims.is_empty() else name


func frame_count(name: StringName) -> int:
	if is_placeholder:
		return 1
	var a: Dictionary = anims.get(resolve_anim(name), {})
	return int(a.get("frames", 1))


func fps(name: StringName) -> float:
	if is_placeholder:
		return 1.0
	return float(anims.get(resolve_anim(name), {}).get("fps", 1.0))


func loops(name: StringName) -> bool:
	if is_placeholder:
		return false
	return bool(anims.get(resolve_anim(name), {}).get("loop", false))


## Resolve (anim, facing, frame) to something drawable, or {} for a placeholder /
## an out-of-range request.
##
## The index formula is PLAN.md 9.1: within an anim, frames are direction-major --
## `first + stored_direction * frames + frame`.
func frame_at(name: StringName, facing: int, frame: int) -> Dictionary:
	if is_placeholder or dir_table.is_empty():
		return {}

	var a: Dictionary = anims.get(resolve_anim(name), {})
	if a.is_empty():
		return {}

	var dir: Dictionary = dir_table[posmod(facing, dir_table.size())]
	var count := int(a["frames"])
	var index := int(a["first"]) + int(dir["stored_index"]) * count + posmod(frame, count)
	if index < 0 or index >= frames.size():
		return {}

	var f: Dictionary = frames[index]
	return {
		"page": int(f["page"]),
		"rect": f["rect"] as Rect2i,
		"anchor": f["anchor"] as Vector2,
		"flip_x": bool(dir["flip_x"]),
	}


## Lazily loaded so that parsing an atlas -- and therefore the whole seam and its
## tests -- never depends on the PNG pages being present or on a rendering
## context existing.
func texture(page: int) -> Texture2D:
	if page < 0 or page >= pages.size():
		return null
	if _textures[page] == null and ResourceLoader.exists(pages[page]):
		_textures[page] = load(pages[page]) as Texture2D
	return _textures[page]
