## Credits screen (PLAN.md 1.4). Surfacing this is a licence obligation, not a
## courtesy -- CREDITS.md §"Adding an entry" requires the 0 A.D./Wildfire
## Games and Kibyra lines below to be reproduced, and `art/LICENSE.txt`
## requires the CC-BY-SA 3.0 link, "Wildfire Games", and wildfiregames.com
## verbatim, not abbreviated.
##
## Hardcoded rather than parsed from CREDITS.md at runtime: that file lives at
## the repo root, outside `res://` (`game/`), so the engine cannot load it as
## a resource. This text is the in-game mirror of it; CREDITS.md itself
## documents that whoever adds a new credited asset must update both in the
## same change.
extends Control

const _MAIN_MENU_SCENE := "res://scenes/menu/MainMenu.tscn"

const _CREDITS_TEXT := """[center][font_size=32][color=#E5B842]AGE OF DRAGON[/color][/font_size]

[font_size=20]Credits[/font_size][/center]

[b]0 A.D. — Wildfire Games[/b]
Unit, building, terrain and prop art, rendered from Wildfire Games' 3D models to 2D isometric sprites.
Licence: Creative Commons Attribution-ShareAlike 3.0 (http://creativecommons.org/licenses/by-sa/3.0/)
http://www.wildfiregames.com/ · https://play0ad.com

[b]Kibyra — UI packs[/b]
UI chrome: panels, buttons, bars, frames and icons.
https://kibyra.itch.io/ui-fonts-dragon-huds-pack · https://kibyra.itch.io/free-medieval-fantasy-ui-pack
Free for personal and commercial use; original files are not redistributed.

[b]App icon, boot splash and menu art[/b]
Generated by the project owner using Google Gemini.

[b]Godot Engine[/b]
https://godotengine.org — MIT Licence

[b]Tools[/b]
isobake (this project's 3D-to-2D sprite pipeline), blender_pyrogenesis_importer, Blender, Pillow, NumPy.

Full provenance: CREDITS.md and game/assets/LICENCES.md in the project repository."""


func _ready() -> void:
	var bg := ColorRect.new()
	bg.color = Color("#2B1D14")
	bg.set_anchors_preset(Control.PRESET_FULL_RECT)
	add_child(bg)

	var margin := MarginContainer.new()
	margin.set_anchors_preset(Control.PRESET_FULL_RECT)
	margin.add_theme_constant_override("margin_left", 120)
	margin.add_theme_constant_override("margin_right", 120)
	margin.add_theme_constant_override("margin_top", 60)
	margin.add_theme_constant_override("margin_bottom", 100)
	add_child(margin)

	var scroll := ScrollContainer.new()
	margin.add_child(scroll)

	var text := RichTextLabel.new()
	text.bbcode_enabled = true
	text.text = _CREDITS_TEXT
	text.fit_content = true
	text.custom_minimum_size = Vector2(800.0, 0.0)
	text.add_theme_color_override("default_color", Color("#EFE0C0"))
	scroll.add_child(text)

	var back := TextureButton.new()
	const back_path := "res://assets/ui/menu/back_button.png"
	if ResourceLoader.exists(back_path):
		back.texture_normal = load(back_path)
	back.ignore_texture_size = true
	back.stretch_mode = TextureButton.STRETCH_KEEP_ASPECT_CENTERED
	back.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
	back.custom_minimum_size = Vector2(180.0, 58.0)
	back.set_anchors_preset(Control.PRESET_BOTTOM_LEFT)
	back.position = Vector2(24.0, -78.0)
	back.pressed.connect(func() -> void: get_tree().change_scene_to_file(_MAIN_MENU_SCENE))
	add_child(back)
