## The procedural map generator (PLAN.md 2.4b), ported into the game from the
## `game_map_gen/` prototype 2026-08-17 with the eight changes PLAN.md 11.2 records.
##
## Produces a `MapData` -- terrain plus an entity list -- never a `SimWorld`. See
## `MapData`'s header for why that indirection carries its weight.
##
## **`generate()` VALIDATES AND RETRIES.** A map that leaves a player walled in is
## unplayable and invisible until someone plays it, so the connectivity gate
## (`MapValidator`) is built into the entry point rather than offered beside it. If
## every attempt fails, the last map comes back with `meta.problems` filled in, so a
## caller can refuse to start rather than being handed something broken with no way to
## tell.
##
## ## Two departures from the prototype worth stating plainly
##
## **Size is by AREA, not by side.** The prototype grew the side linearly with player
## count, so 8 players got 8x the side and **64x the area** of 2. A player needs about
## one debug map's worth of room (2.4a calls 64x64 generous for one), so the side is
## `64 * sqrt(players)`: 2P 96, 4P 128, 8P 184. This is the single most consequential
## number here, because **fog of war is one byte per tile per player** -- a 300x300 map
## would put ~90 KB of vision into every snapshot, against the 4 KB measured today.
##
## **The generated map is SENT to joining clients, not regenerated by them.** 2.4a's
## rule was that each client builds its own world from the shared `MatchConfig`, which
## holds for the hand-built debug map because it is integer code. This generator uses
## `FastNoiseLite`, whose float maths is not guaranteed identical between an ARM phone
## and an x86 desktop -- and a host and client that disagree about where the water is
## have desynced before the first order, in the one way `state_hash()` cannot help
## with because it would report the divergence without saying why. A `MapData` is
## ~10-25 KB (`to_dict()`), sent once at match start. Certainty for one small message.
class_name MapGenerator
extends RefCounted

## RANDOM resolves to one of the real types at generation time, so the skirmish screen
## can offer it as a choice (1.6) without the caller having to roll it.
##
## **APPENDED, ALWAYS.** `MatchConfig.map_type` is stored as an int and a saved map
## records it (2.4c), so inserting a type in the middle would silently turn every
## recorded Desert into a Forest. ARCHIPELAGO went on the end for that reason and the
## next one will too.
enum Type { RANDOM, ISLAND, RIVER, DESERT, FOREST, ARCHIPELAGO }

const MIN_PLAYERS := 2
const MAX_PLAYERS := 8

## One player's comfortable room, per 2.4a's note on the 64x64 debug map. The side is
## derived from `BASE_SIDE * sqrt(players)` and rounded up to a multiple of
## `SIDE_MULTIPLE`, purely so sizes read as round numbers.
const BASE_SIDE := 64
const SIDE_MULTIPLE := 16

## Ground cleared around a start, BEYOND the town centre's own footprint, on every
## side. A 10x10 town centre therefore gets a 22x22 clearing.
const START_CLEARANCE := 6
## Chebyshev radius from the start centre for the villagers and the scout. The town
## centre's footprint reaches radius 5, so 7 leaves two clear tiles between the wall
## and the nearest unit -- the prototype's radius 4 put every villager INSIDE its own
## town centre.
const UNIT_RING_RADIUS := 7
## How far from the start centre a resource vein begins (the owner's figure).
const VEIN_DISTANCE := 9
## Tiles of each kind to try to place per start.
const STONE_TILES := 35
const GOLD_TILES := 12
## Hard ceiling on a vein's random walk. The prototype had none, and counted only
## pixels it actually wrote -- so a vein that walked off the map wrote nothing, never
## reached its target, and span.
const VEIN_MAX_STEPS := 400

## Trees are placed as COPSES on scattered anchors, not one per tile of a wood region,
## and **the density is a wire-format decision rather than a cosmetic one**: every tree
## is a `SimResourceNode` in `entities`, and the snapshot carries entities.
##
## Two numbers found by looking at the output. A one-per-tile forest put **1472 trees**
## on a 96x96 map and made the map 209 KB to send. Thinning that to a strict lattice
## fixed the count and produced a visible REGULAR GRID of single trees — an orchard,
## and the lattice spacing readable straight off the picture. So: anchors on a coarse
## lattice, each carrying a small jittered clump, which gives the same count grouped
## into woods with clearings between them.
##
## The trade is worth naming: **AoE-style solid forest is not affordable under a
## full-state snapshot** (7.2). A wood here is a handful of rich trees rather than a
## thousand poor ones — `res.tree` carries up to 175 wood a node, so a copse is worth
## walking to. A real delta encoding is what would buy the dense version.
const TREE_CLUMP_SPACING := 8

## A LIGHT SCATTER OF SINGLE TREES OVER THE WHOLE BOARD, off the wood mask entirely
## (project owner, 2026-08-30: *"we need to light sprinkle trees over the rendered
## maps"*, in the same breath as doubling `res.tree`'s amounts).
##
## **THE COPSES ANSWER TO THE MASK AND THIS ANSWERS TO NOTHING**, which is the point of
## it being a separate pass. `_place_trees` only ever puts wood where the terrain noise
## already said wood may go, so a desert's open sand, a river map's far bank and every
## stretch of grass between two woods came out completely bare -- and a player who had
## worked out the last copse on their half of the map had no wood left anywhere they
## could see. A tree every so often over open ground is both the buffer and the reason
## the ground reads as landscape rather than as a billiard table.
##
## **ONE TREE PER ANCHOR, NOT A CLUMP.** A clump out here would be a wood, and a wood
## that the mask did not put there undoes the shape the noise was tuned for -- SHAPE's
## own note is three paragraphs about getting distinct woods with lanes between them.
## Singles read as scattered growth and cannot merge into anything.
##
## SPACING IS SCALED BY `tree_spacing` LIKE EVERY OTHER LATTICE HERE, so the count is
## flat across board sizes rather than growing with the area: 16 on a 96x96 board is 36
## anchors, of which the water, the clearings and the woods take a good share. That is
## a few per cent on top of a forest map's ~1,300 trees and roughly a fifth on top of a
## desert's, which is the direction that matters -- the sparse maps are the ones that ran
## out. **The ceiling is `AISystem`'s per-tick linear searches and not the snapshot**;
## see `SHAPE`'s note on the `clump: 9` attempt that hung a session at ~1,300 trees.
const SPRINKLE_SPACING := 16

## How far a sprinkled tree keeps clear of a start, BEYOND `_clear_base`'s own radius.
##
## `_clear_base` zeroes the wood MASK over its clearing, which is what keeps copses out
## of a base -- and this pass does not read the mask, so without an explicit distance it
## would drop trees inside the town centre's footprint and across the ring the starting
## villagers stand on. The extra tiles past the clearing are so the first house does not
## have to be sited around an oak.
const SPRINKLE_START_CLEARANCE := 8

## One copse, as tile offsets from its anchor. A loose blob rather than a solid square,
## so the sprites overlap into a canopy with gaps of light in it.
##
## THE FIRST FIVE ARE THE ORIGINAL SHAPE and every map type except the forest still
## takes exactly those, in that order -- the four after them are the forest's extra
## density (see `SHAPE`) and were appended rather than interleaved so that changing how
## thick a wood is cannot quietly move the copses on a river map.
const TREE_CLUMP_SHAPE := [
	Vector2i(0, 0), Vector2i(2, 0), Vector2i(1, 2), Vector2i(3, 2), Vector2i(0, 3),
	Vector2i(4, 0), Vector2i(2, 4), Vector2i(4, 3), Vector2i(1, 4),
]

## Trees placed around every start regardless of map type, in a loose ring this far out.
##
## **Start resources are PLACED, not sampled.** The first version left them to the
## terrain noise and the validator immediately caught what that costs: a desert start
## had one reachable tree and no food at all. Every real RTS map generator guarantees
## an opening; hoping the noise put a wood nearby is how a player gets a start they
## cannot play.
const START_WOOD_COUNT := 8
const START_WOOD_MIN := 11
const START_WOOD_MAX := 17
const START_FOOD_COUNT := 4

## WILDLIFE, PER START (project owner, 2026-08-23). The debug map got animals when the
## wolf landed and this generator did not, so a generated match had none at all -- which
## is what the owner hit: "i did not find any wildlife at all".
##
## PER START rather than scattered over the whole board, and that is a fairness choice
## rather than a literal reading of "x2 per player". Sprinkling 2n animals at random
## across the map gives them all to whoever the noise favours; hanging them off each
## start gives every player the same opening and still lands them at a random angle and
## distance. The COUNT is what "per player" was about, and the count is exact.
##
## Distances are banded by what the thing is for. Sheep are an opening food source and
## sit just past the berry ring; deer are a second wave worth walking to; the wolf is a
## hazard you should meet by exploring, not by stepping outside. Nothing is placed
## nearer the base than `WOLF_MIN` allows, which is the number that matters: at aggro 6
## against five villagers, close means eating the opening before the player has read the
## screen.
const SHEEP_HERDS := 2
const SHEEP_PER_HERD := 3
const SHEEP_MIN := 13
const SHEEP_MAX := 19

const DEER_HERDS := 2
const DEER_PER_HERD := 7
const DEER_MIN := 19
const DEER_MAX := 27

## ONE PREDATOR SPECIES PER MAP TYPE (project owner, 2026-08-23): "i dont want to
## many angry mobs on one map". So the map decides which animal is hunting you, and a
## match has one kind of danger rather than three overlapping ones.
##
## It also makes the four map types feel different for a reason other than terrain,
## which they did not before -- a river map and a desert map played identically once
## you were past the water. Now a forest is where the bear is.
##
## The pairings are the owner's. The counts and distances are mine, banded by how
## dangerous the animal is: the bear is alone because at 150 hp and 10 damage two of
## them per player is not a hazard, it is a siege.
const PREDATORS := {
	Type.DESERT: {"def": &"unit.wolf", "count": 2, "min": 24, "max": 33},
	Type.RIVER: {"def": &"unit.wolf", "count": 2, "min": 24, "max": 33},
	Type.FOREST: {"def": &"unit.bear", "count": 1, "min": 22, "max": 32},
	# Nearer, because an island's land is a fraction of its board and a boar placed
	# out at the wolf's range would spend most of its rolls in the sea.
	Type.ISLAND: {"def": &"unit.boar", "count": 2, "min": 15, "max": 24},
}

## How far a herd's animals spread from the anchor the herd was placed at. Small: a
## flock reads as a flock only if the sprites nearly touch, and seven deer spread over
## eight tiles is not a herd, it is seven deer.
const HERD_SPREAD := 3

## THE DRAGON NEST AND HER MOTHER, ONE PER MAP (PLAN.md 13.2).
##
## ⚠️ **THIS IS THE WHOLE UNIQUENESS MECHANISM, AND THAT IS DELIBERATE.** A `UnitDef.limit`
## plus a `UnitLimitSystem` was built and tested on 2026-09-04 against a reading in which
## the castle trained dragons; the owner settled that there is no castle route, which left
## the cap with no consumer at all and it was deleted. *"Uniqueness for the dragon is now a
## MapGen property: place one nest, place one mother."* So the guarantee lives here, in one
## call at the bottom of `_generate_once`, and nothing anywhere else has to be asked.
##
## **A CONTESTED MIDPOINT, WHICH IS WHY IT IS SEARCHED FROM THE MAP CENTRE.** The claim
## rule is "kill her, then hold the nest for 360 s while the baby grows", so the nest has
## to be ground somebody can be *denied*. At the centre it is roughly equidistant from
## every start on every layout the four ring-based types produce, and the search widens
## outward, so the site stays as near the middle as the terrain and the clearance allow.
##
## **NO RNG DRAW REACHES ANYTHING ELSE.** The nest goes in after `_place_base` and before
## `_place_trees`, and both tree passes are pure hashes of the anchor -- so this consumes
## from the stream at a point where nothing downstream reads it. Every existing seed keeps
## the terrain, veins, herds and copses it always had, with a nest added on top. That is
## the same property `_sprinkle_trees` documents having preserved, and it is not luck: it
## is why the call sits where it does.
const NEST_DEF := &"building.dragon_nest"
const NEST_GUARDIAN_DEF := &"unit.dragon"

## Slack beyond the arithmetic floor `nest_start_clearance()` computes. See there.
const NEST_CLEARANCE_SLACK := 7

## How far past the nest's own footprint the mother stands, in tiles.
##
## ONE TILE OUT, AND SHE MAY NOT STAND ON IT. A unit's entry claims the tile it is on as
## far as placement goes (`MapData.footprint_rect_of`), so a dragon on the nest's centre is
## an entity overlapping another entity -- which `MapValidator._overlapping_entities`
## counts, which fails the map, which retries eight times and hands back an unplayable one.
## It costs nothing: she adopts the nest as her post on her first tick
## (`WildlifeSystem.POST_RADIUS`), so where exactly she was stood is not where she lives.
const NEST_GUARDIAN_RING := 1


## How far the nest keeps clear of every start, in tiles.
##
## ⚠️ **DERIVED FROM HER AGGRO RADIUS RATHER THAN WRITTEN DOWN, and that is the lesson
## `MapGen.DEBUG_ENEMY_SQUAD` paid for**: a placement pinned to a literal goes quietly wrong
## the day the radius it was chosen against is retuned. The floor is arithmetic:
##
##     aggro_radius (10)  the guard circle around the nest -- `UnitDef.guards_post`
##   + UNIT_RING_RADIUS (7)  where the starting villagers and the scout stand
##   ------
##     17                 the distance at which an opening villager is NOT already inside it
##   + NEST_CLEARANCE_SLACK (7)  room for the first houses and fields forward of the ring
##
## **AND IT IS ONLY SATISFIABLE BECAUSE A GUARDIAN'S AGGRO IS MEASURED FROM HER POST.**
## Measured from the animal, the circle drifts with her wandering: `roam_radius` 8 plus the
## nest's half-extent means she reaches 14 tiles out, so the floor would be 31 -- and the
## two-player board puts its starts 30 tiles from the centre. There is no clearance a 96-tile
## map can afford that keeps a 600 hp flyer out of an age-1 opening under the roaming rule.
## The fix was the rule, not the number.
static func nest_start_clearance() -> int:
	return nest_guard_radius() + UNIT_RING_RADIUS + NEST_CLEARANCE_SLACK


## How far the mother will pick a fight, measured from the nest -- her `aggro_radius`.
##
## READ OFF THE ROSTER so the placement moves with a retune, and defaulted rather than
## asserted so a project without the def still generates a map. **It is a radius around the
## NEST and not around her**, which is `UnitDef.guards_post`'s whole subject; the two
## placement rules below both depend on that being true.
static func nest_guard_radius() -> int:
	var d: UnitDef = GameDataRegistry.unit(NEST_GUARDIAN_DEF)
	return d.aggro_radius if d != null else 10

## FISH, per start, in SHALLOW water only (6.5). Deep water is excluded on purpose --
## it is what an island's middle ocean is made of, and a shoal five tiles from any
## shore is a food source a player can see and never reach until they have a dock and a
## ship, which is precisely the frustration the whole guaranteed-opening rule exists to
## avoid. Shallow is the rim and the river, which is where a dock can actually go.
##
## Best-effort like every placer here, and more so: a start with no water in range gets
## no fish, which is the right answer rather than a failure. A desert oasis map will
## come out with a couple and an island with the full count.
const FISH_COUNT := 5
const FISH_MIN := 8
const FISH_MAX := 26

## How many anchors a herd may try before giving up on that herd entirely. A herd is
## seven animals in one throw, so losing one to a single unlucky angle is a visible
## hole where losing one scattered berry bush is not.
const ANCHOR_ATTEMPTS := 8

## How many times to regenerate before giving up on validation.
const MAX_ATTEMPTS := 8

## Noise shape per map type. **Tune these by running
## `dev_preview/preview_mapgen.tscn` and looking**, which is the only way to judge
## them -- the numbers say nothing on their own.
##
## `freq` is feature SIZE (lower = bigger, smoother regions) and `wood` is the
## threshold above which a tile may carry trees. The two together set both the look
## and the tree count, and the count is a wire-format cost -- see TREE_CLUMP_SPACING.
##
## **They are two separate knobs, and moving both at once is how this went wrong
## twice.** `freq` is a WAVELENGTH: features come out about `1 / freq` tiles across, so
## it sets the SIZE of a wood. `wood` is a percentile cut on the noise, so it sets what
## FRACTION of the map is wooded — and therefore the tree count, which is a wire cost.
##
## The mistake worth recording, because it is counter-intuitive: chasing "bigger, more
## connected woods" by lowering the frequency to 0.010 made it worse, not better. At
## 0.010 the wavelength is ~100 tiles, which on a 96-tile map is a single gradient
## across the whole thing — so a threshold anywhere near the middle covers most of the
## map fairly evenly and the copses spread out over all of it. **Distinct woods with
## lanes between them need a wavelength a few times SMALLER than the map**, around
## 25-35 tiles, i.e. `freq` about 0.03. Small features with a high threshold (the first
## attempt, 0.018/0.12) gives confetti; large features with any threshold gives a wash;
## the middle gives woods.
##
## `spacing` and `clump` are the DENSITY knobs and only the forest sets them (project
## owner, 2026-08-28: *"forest map type needs to be fully tree populated, dense growth
## with a small clearing or road with no trees between the players"*). `spacing` is the
## lattice the copses are anchored on and `clump` is how many of `TREE_CLUMP_SHAPE`'s
## offsets each one uses; everything else takes the defaults, which are the numbers every
## other map type has always had.
##
## Measured on seed 1, 2 players, 96x96: **185 trees before this and 482 after**, with
## the MAP's own wire size going 47.6 KB -> 86.8 KB. A forest map is deliberately the
## expensive one; a river map has no reason to pay for it, which is why these are
## per-type.
##
## **THE FIRST ATTEMPT WAS `clump: 9` AND IT HUNG A SESSION.** That put ~1,300 trees on
## this board, and the thing it broke was not the one the note above predicts:
##
##   - the SNAPSHOT was fine and always would have been. `TREE_CLUMP_SPACING`'s note
##     quotes 209 KB as unaffordable, and that figure is the MAP, sent once, not the
##     snapshot sent ten times a second. `preview_wire_size` read **9.1 KB at tick 1 and
##     14.8 KB at tick 3600 with 50-72 nodes in view**, because `SnapshotSystem` filters
##     by vision (12.1f): a player can only ever see a screenful of wood.
##   - **CPU was the wall.** `AISystem` searches the whole entity list per player per
##     tick -- nearest node, nearest enemy, who is idle -- so quadrupling the list
##     quadrupled that. `test_tick_cost` measured **24.83 ms a tick against its 20 ms
##     ceiling** for a 2-player AI match, and the project owner hit it as a hang before
##     the suite reported it as a number.
##
## So the wood is as thick as the tick budget affords and no thicker. **If a denser
## forest is wanted, the lever is `AISystem`'s linear searches** -- a spatial query for
## "nearest node of kind K" would take the dominant term out and let this go back up.
## Density is not the thing standing in the way; a per-tick full scan is.
const SHAPE := {
	Type.FOREST: {"freq": 0.035, "wood": -0.30, "lake": 0.52, "spacing": 6, "clump": 3},
	Type.RIVER: {"freq": 0.030, "wood": 0.28, "lake": 1.0},
	Type.ISLAND: {"freq": 0.040, "wood": 0.10, "lake": 1.0},
	Type.DESERT: {"freq": 0.030, "wood": 0.05, "lake": 1.0},
	# The archipelago paints its own islands and never consults `wood` or `freq` for the
	# terrain -- only `_place_trees` reads this, and only for `spacing`/`clump`. The
	# entries are here because `SHAPE[resolved]` is unconditional and a type missing from
	# this table would crash rather than default; the tree numbers are the standard ones.
	Type.ARCHIPELAGO: {"freq": 0.040, "wood": 0.10, "lake": 1.0},
}

## ARCHIPELAGO (2.4d, PLAN.md 11.6): one island per player, a few sheep, nothing that
## bites. A quiet opening and a naval midgame -- you cannot be attacked until somebody
## crosses, so the pressure is economic and the first fight is a landing.
##
## **THE ISLAND RADIUS WAS SET BY THE VALIDATOR AND IS NOW SET BY WHAT FITS ON IT.**
##
## It shipped at 18, which is the FLOOR: `MapValidator.MIN_NEARBY` wants 4 wood, 1 gold, 1
## stone and 1 food within a walk of the start, and `_place_base` puts them at
## `VEIN_DISTANCE` 9 and `START_WOOD_MIN/MAX` 11-17, so an island whose land stops before
## 18 tiles cannot pass its own opening whatever it looks like. The note here then argued
## that nothing above the floor bought anything, because *"bigger islands are a land map
## with a moat"*.
##
## ⚠️ **THAT ARGUMENT IS REVERSED, project owner 2026-08-30:** *"the archipelago map type
## is so small you cannot fit half of the building from age 2 on it."* They are right and
## it is arithmetic rather than taste. A disc of radius 18 is ~1,020 tiles; the base
## clearing alone is ~380 of them, the guaranteed opening claims 35 stone tiles, 12 gold,
## 8 trees and a berry ring, and what is left has to hold a market (8x8), a barracks
## (6x6), an archery range (7x6), fields at 6x6 each and eight houses. It does not.
## Radius 26 is ~2,120 tiles, which is roughly double the ground and a little over the
## 2.4a note's *"64x64 is generous for one player"*.
##
## **THE MAP NOW GROWS TO FIT THE ISLAND, WHERE THE ISLAND USED TO SHRINK TO FIT THE
## MAP** -- see `archipelago_side`. Raising this number ALONE would have made the islands
## SMALLER, which is the trap worth recording: `_archipelago_ring_radius` subtracts this
## from the half-side, so a bigger island pulls the start ring inward, which shortens the
## chord between neighbours, which is exactly what `_island_radius` caps against. At 26 on
## the old 96-tile two-player board the cap lands at 12. The dependency had to be turned
## round, not re-tuned.
const ISLAND_RADIUS := 26

## How far the land stops short of the map edge, so an island reads as an island rather
## than as the map running out. Also the gap the ring radius is derived against.
const SEA_MARGIN := 5

## How ragged a coastline is, as a fraction of the radius. LOWER THAN `_paint_island`'s
## 0.35 on purpose: that one carves a single landmass and can afford a wild edge, and
## here 0.35 grows each island's effective radius to 1.35x, which on a two-player 96-tile
## board is the difference between ten tiles of sea between neighbours and none at all.
## An archipelago whose islands have merged is a land map that took the long way round.
const ISLAND_RAGGED := 0.20

## PER-TYPE CONTENT, for the things `_place_base` would otherwise give every map equally.
## Absent keys take the constants above, so this stays a list of DIFFERENCES rather than
## a second copy of the defaults -- and a new type that wants the standard opening adds
## nothing here at all.
##
## The archipelago's three, and each is a consequence of the island rather than a taste:
## a herd of seven deer on a one-base island is most of an opening's food standing still,
## so there are none; sheep drop to one herd for the same reason ("a few", the owner's
## word); and fish go UP because the sea is the point and it is the one type where a dock
## is not a luxury. Predators need no entry -- `PREDATORS` is read with `.get(type, {})`,
## so an unlisted type gets nothing that bites for free, which is exactly the requirement.
##
## ⚠️ **AND ITS WOOD, which is the fourth and was MEASURED rather than judged.** The
## 2026-08-30 wood pass (`resources.json`'s note) doubled every tree and added
## `_sprinkle_trees`, and a count of what each type actually holds afterwards put the
## archipelago last by a wide margin: **1,971 wood per player at eight players**, against
## 4,025 on a desert and 54,600 on a forest. A town centre is 275 of that and a mill 100,
## so a player on the map whose whole point is a NAVY -- a galley is 90 wood and a
## galleon 200 -- could not pay for both a second base and a fleet.
##
## Neither half of that pass could reach this type. The mask is what the copses read and
## an island's is nearly empty; the sprinkle lattice is laid over the whole BOARD, and 92%
## of this one is sea, so it landed **one** tree on a two-player map. So the wood comes
## through the guaranteed opening instead, which is the mechanism this file already trusts
## for exactly this situation -- see `START_WOOD_COUNT`'s note on what leaving a start's
## resources to the noise cost the first time.
##
## 20 rather than 8, out to 22 tiles rather than 17: the band has to widen with the count
## or twenty trees ring the town centre like a hedge, and `ISLAND_RADIUS` 26 is what says
## 22 is still on dry land.
const CONTENT := {
	Type.ARCHIPELAGO: {"sheep_herds": 1, "deer_herds": 0, "fish": 9,
			"start_wood": 20, "start_wood_max": 22},
}

## How wide the LANE between two players is kept clear of trees, in tiles either side of
## the line joining them (project owner: *"a small clearing or road with no trees between
## the players"*).
##
## FOREST ONLY, and it is the other half of making the wood thick: at `wood: -0.30` most
## of the board is trees, so without this two players on a 96-tile map are separated by
## sixty tiles of solid canopy and the first contact of the game is a lumberjacking
## expedition. It clears the WOOD MASK and not the terrain -- the ground under a lane is
## ordinary grass that was never going to be anything else, so nothing about
## passability, building or the validator changes.
##
## 3 either side is 7 tiles wide with the centre line: two units abreast plus room to
## path around each other, and narrow enough to read as a road through a wood rather
## than as a field with trees at the edges.
const LANE_HALF_WIDTH := 3


## Side length in tiles for `players`, by AREA per player. See the class header.
static func side_for(players: int) -> int:
	var count := clampi(players, MIN_PLAYERS, MAX_PLAYERS)
	var ideal := float(BASE_SIDE) * sqrt(float(count))
	return int(ceil(ideal / float(SIDE_MULTIPLE))) * SIDE_MULTIPLE


## Side length for one map TYPE, which is `side_for` for everything but the archipelago.
##
## Kept as a separate function rather than folded into `side_for`, because `side_for` is
## the answer to *"how much room do N players want"* and is asked by the lobby, by the
## tests and by `spacing_for`'s reference board. This is the answer to *"how big must the
## board be for the map I am about to paint"*, which only the generator asks.
static func side_for_type(type: Type, players: int) -> int:
	return archipelago_side(players) if type == Type.ARCHIPELAGO else side_for(players)


## AN ARCHIPELAGO IS SIZED BY ITS ISLANDS, not by the area-per-player rule (2026-08-30).
##
## Every other map type is land you divide up, so `side_for`'s *"one debug map's worth of
## room each"* is the right question. An archipelago is not: most of its board is sea, so
## a board sized as though it were land gives each player a fraction of a player's ground
## -- which is the project owner's *"you cannot fit half of the building from age 2 on
## it"*, and it is why `ISLAND_RADIUS`'s note now records a reversal.
##
## **THE GEOMETRY, RUN BACKWARDS.** `_island_radius` derives an island from the board by
## capping it at half the chord between neighbouring starts, less a sea margin. This
## solves the same relation for the board instead: the chord must hold two island radii
## and two margins, `chord = 2 * ring * sin(PI / n)`, and the board must hold the ring
## plus one more island and margin on the far side. So the island is the constant and the
## side is what falls out -- 128 at two players, 160 at four, 224 at eight, against
## `side_for`'s 96 / 128 / 192.
##
## The `+ 1.0` is a tile of slack against the integer truncation in `_island_radius`,
## which is the thing that would otherwise turn a rounding hair into an island one tile
## short of what this promised. Rounding UP to `SIDE_MULTIPLE` usually supplies plenty on
## its own; at eight players the exact answer lands on a multiple and there is none.
##
## Floored at `side_for`, so this can only ever grow a board. An archipelago is at worst
## as roomy as the land map for the same player count, never tighter.
static func archipelago_side(players: int) -> int:
	var n := clampi(players, MIN_PLAYERS, MAX_PLAYERS)
	var island := float(ISLAND_RADIUS + SEA_MARGIN)
	var ring := island / sin(PI / float(n))
	var half := ring + island + 1.0
	var side := int(ceil(2.0 * half / float(SIDE_MULTIPLE))) * SIDE_MULTIPLE
	return maxi(side_for(n), side)


## A validated map. `meta.problems` is empty on success; if it is not, every attempt
## failed and the caller should refuse to start (1.6 disables Start on it).
##
## `size_players` SIZES THE MAP FOR A DIFFERENT NUMBER THAN IT PLACES. Two counts,
## because the lobby learned to close a slot (12.1c): choosing eight players and closing
## six is a request for a map with eight players' worth of room and two people in it.
##
## Passing `players` alone would ruin exactly that. Starts are spread evenly around a
## ring for the count they are placed for, so two starts on an eight-start ring sit 45
## degrees apart -- two players cheek by jowl in one corner of a 192x192 board, which is
## the opposite of what asking for a big map meant. Placing two starts on a map SIZED for
## eight puts them 180 degrees apart, which is.
##
## 0 means "the same as players", so every existing caller keeps the square map it had.
static func generate(p_seed: int, type: Type, players: int,
		size_players: int = 0, attempts: int = MAX_ATTEMPTS) -> MapData:
	var count := clampi(players, MIN_PLAYERS, MAX_PLAYERS)
	var size_count := clampi(size_players if size_players > 0 else count,
			MIN_PLAYERS, MAX_PLAYERS)
	# A map cannot be smaller than the people standing on it. Guards a caller that closes
	# slots and then raises the count of open ones without regenerating.
	size_count = maxi(size_count, count)
	var last: MapData = null

	for attempt in range(maxi(1, attempts)):
		# A DERIVED seed, not a re-roll: attempt N of seed S is reproducible, so a
		# map that took three tries can still be recovered from the seed the player
		# was shown. Mixed rather than incremented so consecutive seeds do not
		# produce near-identical maps.
		var attempt_seed := p_seed ^ (attempt * 0x9E3779B9)
		last = _generate_once(attempt_seed, type, count, size_count)
		var problems := MapValidator.problems(last)
		last.meta["seed"] = p_seed
		last.meta["attempt"] = attempt
		last.meta["problems"] = problems
		if problems.is_empty():
			return last

	return last


static func _generate_once(p_seed: int, type: Type, count: int, size_count: int) -> MapData:
	var rng := RandomNumberGenerator.new()
	rng.seed = p_seed

	var resolved := type
	if resolved == Type.RANDOM:
		var choices := real_types()
		resolved = choices[rng.randi_range(0, choices.size() - 1)]

	# Sized for one count, populated for another. See `generate`. BY TYPE since
	# 2026-08-30: an archipelago is sized by what has to fit on its islands rather than by
	# area per player -- `archipelago_side`.
	var side := side_for_type(resolved, size_count)
	var data := MapData.create(Vector2i(side, side))

	# 1 where a tree MAY stand. Kept beside the terrain rather than painted into it as
	# `Terrain.FOREST`, because a tree is an entity standing on walkable ground (2.3) --
	# the same arrangement the debug map uses. Chopping a wood then leaves grass
	# behind with nothing to convert.
	var wood := PackedByteArray()
	wood.resize(side * side)

	# AN ARCHIPELAGO IS PAINTED AROUND ITS STARTS AND EVERY OTHER TYPE IS PAINTED FIRST,
	# and the order is forced rather than chosen. Every other painter lays a landscape and
	# then `_start_positions` finds somewhere on it to stand; an archipelago has no
	# landscape until it knows where the islands go, because the islands ARE the starts.
	# So this is the one type whose terrain is a function of its start ring instead of the
	# other way round.
	if resolved == Type.ARCHIPELAGO:
		data.fill_terrain(SimMap.Terrain.WATER_DEEP)
		data.starts = _archipelago_start_positions(data, count, rng)
		_paint_archipelago(data, wood, rng, data.starts, count)
	else:
		match resolved:
			Type.ISLAND:
				_paint_island(data, wood, rng)
			Type.RIVER:
				_paint_river(data, wood, rng)
			Type.DESERT:
				_paint_desert(data, wood, rng)
			_:
				_paint_forest(data, wood, rng)
		data.starts = _start_positions(data, resolved, count, rng)

	# Clear every base BEFORE placing anything, so one player's clearing cannot wipe
	# out the town centre of a neighbour whose start landed close by.
	for centre in data.starts:
		_clear_base(data, wood, centre)

	# AFTER the clearings and BEFORE anything is placed on the ground. Both halves of
	# that were found by a failing test rather than reasoned out. `_clear_base` paints
	# GRASS over its whole radius, so a shore pass run before it gets overwritten and a
	# base sited by the water goes straight back to a hard green-on-blue edge -- which
	# is precisely the case a player is most likely to be looking at. Running it after
	# `_place_base` instead would grow beaches under nodes already standing there.
	#
	# Sand is buildable and walkable ground (`SimMap.DOMAIN_TERRAIN`), so a clearing
	# that turns out to be half beach costs the player nothing.
	_paint_shores(data, wood, rng)

	var claimed: Dictionary = {}
	for i in range(count):
		_place_base(data, claimed, i + 1, data.starts[i], resolved, rng)

	# THE DRAGON NEST, after every base and before every tree (PLAN.md 13.2). After the
	# bases because the guaranteed opening outranks a POI and `claimed` has to be complete
	# before the nest looks for 100 free tiles; before the trees because they read
	# `claimed` and would otherwise grow a copse through the henge.
	_place_nest(data, claimed, rng)

	# THE LANE GOES IN BEFORE THE TREES, not by removing them afterwards. Clearing the
	# mask means the copses are never anchored in the road at all, so a lane cannot come
	# out as a corridor with half-clumps hanging into it.
	var road: Dictionary = {}
	if resolved == Type.FOREST:
		road = _clear_lanes(data, wood)

	var shape: Dictionary = SHAPE[resolved]
	_place_trees(data, wood, claimed, tree_spacing(shape, data.size),
			int(shape.get("clump", 5)))

	# AFTER the copses, and last of everything (2026-08-30). It ignores the wood mask, so
	# it has to run when every other placer has staked its ground: `claimed` is what keeps
	# a sprinkled tree off a vein, a herd, a berry ring and a copse alike, and it is only
	# complete now. Running it earlier would also let it steal tiles the guaranteed
	# opening needs, which is the one thing on this map that may not be crowded out.
	_sprinkle_trees(data, claimed, spacing_for(SPRINKLE_SPACING, data.size), road)

	data.meta["type"] = int(resolved)
	# BOTH counts recorded. `players` is how many start here; `size_players` is how many
	# it was sized for, and they differ whenever the lobby closed a slot. A saved map
	# (2.4c) that recorded only one of them could not be reopened as the map it was.
	data.meta["players"] = count
	data.meta["size_players"] = size_count
	data.meta["format_version"] = MapData.FORMAT_VERSION
	return data


static func type_name(type: Type) -> String:
	match type:
		Type.ISLAND: return "Island"
		Type.RIVER: return "River"
		Type.DESERT: return "Desert"
		Type.FOREST: return "Forest"
		Type.ARCHIPELAGO: return "Archipelago"
		_: return "Random"


## This map type as a VARIANT POOL name (visuals.json `variant_pools`), which is how
## the project owner's per-map tree assignment reaches the view -- palms on an island,
## dead wood in the desert -- without either side learning the other's vocabulary.
##
## RANDOM answers "" rather than "random", and that is the useful part: a pool name
## nothing declares falls back to the plain `variants` list, so the fixed debug map and
## every preview and test draw the oak/elm/toona mix instead of resolving to a biome
## they were never given. `meta.type` is always a resolved type by the time anything
## asks, so the empty case is the "nobody told me" case and not a real map.
##
## Lowercased `type_name` rather than a second table: one spelling, decided here.
static func pool_name(type: Type) -> StringName:
	return &"" if type == Type.RANDOM else StringName(type_name(type).to_lower())


## Every pool name a real map can present. `GameDataRegistry._validate_variants` checks
## visuals.json against this, so a pool keyed "islands" or "jungle" fails the suite at
## load rather than silently never being chosen -- the failure a data-driven lookup
## gives you for free is no failure at all.
static func pool_names() -> Array[StringName]:
	var out: Array[StringName] = []
	for t in real_types():
		out.append(pool_name(t))
	return out


## Every type RANDOM may roll and the picker may offer -- which is every value of `Type`
## except RANDOM itself.
##
## ONE LIST, THREE CALLERS, and the reason is a bug this file shipped with: `generate()`
## used to index `[ISLAND, RIVER, DESERT, FOREST]` by hand, `pool_names()` wrote the same
## four out again, and `skirmish_screen` wrote them a third time. Adding a fifth type
## therefore had three places to remember and no failure if you missed one -- RANDOM would
## simply never roll it, silently, forever.
static func real_types() -> Array[Type]:
	return [Type.ISLAND, Type.RIVER, Type.DESERT, Type.FOREST, Type.ARCHIPELAGO]


# ── terrain ─────────────────────────────────────────────────────────────────

static func _noise(rng: RandomNumberGenerator, frequency: float) -> FastNoiseLite:
	var n := FastNoiseLite.new()
	n.seed = rng.randi()
	n.frequency = frequency
	return n


static func _paint_island(data: MapData, wood: PackedByteArray,
		rng: RandomNumberGenerator) -> void:
	var side := data.size.x
	data.fill_terrain(SimMap.Terrain.WATER_DEEP)
	var centre := Vector2(side, side) * 0.5
	var max_radius := float(side) * 0.44
	var shape := _noise(rng, 0.025)
	var trees := _noise(rng, 0.05)

	for y in range(side):
		for x in range(side):
			var t := Vector2i(x, y)
			var dist := Vector2(x, y).distance_to(centre)
			# Radial mask with a noisy coastline, so the island is round-ish but not
			# a circle.
			var land := (1.0 - dist / max_radius) + shape.get_noise_2d(x, y) * 0.35
			if land <= 0.18:
				# A shallow rim, so the shoreline reads as a beach rather than a cliff
				# into deep water.
				if land > 0.02:
					data.set_terrain(t, SimMap.Terrain.WATER_SHALLOW)
				continue
			data.set_terrain(t, SimMap.Terrain.SAND if land < 0.30 else SimMap.Terrain.GRASS)
			if land > 0.34 and trees.get_noise_2d(x, y) > 0.15:
				wood[data.index_of(t)] = 1


## ONE ISLAND PER START, in an open sea (2.4d, PLAN.md 11.6).
##
## Each island is the same radial mask `_paint_island` uses for its single landmass --
## a noisy circle with a shallow rim -- stamped once per start instead of once per map.
## Written with `maxf` rather than by overwriting, so where two islands did come close
## the higher land wins and the coast between them stays a coast; a plain second pass
## would let the later island's deep water erase the earlier one's beach.
##
## THE RING IS DERIVED FROM THE ISLAND, NOT TUNED. `_archipelago_start_positions` puts
## the starts as far out as the map allows once an island and a sea margin are subtracted
## -- so separation is whatever is left over, and it grows with the board rather than
## needing a factor per player count. It comes out at roughly 10 tiles of open water
## between neighbours at 2 players and 16 at 8, because the map grows by area while the
## ring grows by radius.
static func _paint_archipelago(data: MapData, wood: PackedByteArray,
		rng: RandomNumberGenerator, starts: Array[Vector2i], count: int) -> void:
	var radius := float(_island_radius(data, count))
	var shape := _noise(rng, 0.025)
	var trees := _noise(rng, 0.05)
	# One noise field for every island rather than one each, so two neighbours never
	# happen to bulge toward each other in the same way -- and so this stays a pure
	# function of the seed however many players there are.
	var reach := int(ceil(radius * (1.0 + ISLAND_RAGGED))) + 2

	for centre in starts:
		for y in range(centre.y - reach, centre.y + reach + 1):
			for x in range(centre.x - reach, centre.x + reach + 1):
				var t := Vector2i(x, y)
				var i := data.index_of(t)
				if i < 0:
					continue
				var dist := Vector2(t - centre).length()
				var land := (1.0 - dist / radius) + shape.get_noise_2d(x, y) * ISLAND_RAGGED
				if land <= 0.18:
					# A shallow rim, so the shoreline reads as a beach rather than a
					# cliff into deep water -- and so a dock has somewhere to go, which
					# on this map type is the difference between playable and sealed in.
					if land > 0.02 and data.terrain[i] == SimMap.Terrain.WATER_DEEP:
						data.set_terrain(t, SimMap.Terrain.WATER_SHALLOW)
					continue
				data.set_terrain(t, SimMap.Terrain.SAND if land < 0.30 else SimMap.Terrain.GRASS)
				if land > 0.34 and trees.get_noise_2d(x, y) > 0.15:
					wood[i] = 1


## How big each island is, capped so two neighbours cannot merge into one landmass.
##
## `ISLAND_RADIUS` is what a start needs to be playable, and the cap is half the gap
## between neighbouring starts less a margin. It is here rather than asserted because a
## slightly small island fails the validator loudly, and a merged pair fails nothing at
## all: it just quietly stops being an archipelago.
##
## **AS OF 2026-08-30 THE CAP SHOULD NEVER BIND, and it is kept anyway.** `archipelago_side`
## now solves this same relation for the board, so the ring is wide enough by construction
## and `ISLAND_RADIUS` wins every time. What is left is a backstop against the two ways
## that could stop being true -- a caller that hands `_paint_archipelago` a board it did
## not size, and a future `MAX_PLAYERS` or `SIDE_MULTIPLE`. A cap that has become
## unreachable is the cheapest thing in this file to keep.
static func _island_radius(data: MapData, count: int) -> int:
	var ring := _archipelago_ring_radius(data)
	var gap := 2.0 * ring * sin(PI / float(maxi(2, count)))
	return mini(ISLAND_RADIUS, maxi(8, int(gap * 0.5) - SEA_MARGIN))


## As far out as the board allows once an island and its sea margin are taken off.
static func _archipelago_ring_radius(data: MapData) -> float:
	return maxf(1.0, float(data.size.x) * 0.5 - float(ISLAND_RADIUS) - float(SEA_MARGIN))


## Starts evenly around that ring, with a random rotation -- the same arrangement
## `_start_positions` uses, on its own radius.
##
## NOT ROUTED THROUGH `_start_positions`, and not `_clamp_start`ed either. Clamping is
## what keeps a start's base on the map, and here the ring is already inside the map by
## construction; clamping an archipelago start would drag an island off its own ring and
## toward a neighbour, which is the one thing the radius is derived to prevent.
static func _archipelago_start_positions(data: MapData, count: int,
		rng: RandomNumberGenerator) -> Array[Vector2i]:
	var centre := Vector2(data.size) * 0.5
	var radius := _archipelago_ring_radius(data)
	var offset := rng.randf_range(0.0, TAU)
	var out: Array[Vector2i] = []
	for i in range(count):
		var angle := offset + float(i) * TAU / float(count)
		out.append(Vector2i(centre + Vector2(cos(angle), sin(angle)) * radius))
	return out


## A CONTINUOUS river with 1-3 NARROW land bridges.
##
## The bridges are the point and they stay (project owner, 2026-08-17). What the
## prototype got wrong was the river: 20-tile bridge gaps in a band left three
## disjoint segments, so it read as three lakes and "players on opposite sides" meant
## nothing. Here the water is unbroken except at the bridges, which are 5 tiles wide.
##
## Sides are decided by the SIGN of the perpendicular distance to the river's centre
## line, so "opposite sides" is a real test rather than an offset that happens to
## work for one direction. The direction itself varies -- the prototype hardcoded the
## `y = x` diagonal.
static func _paint_river(data: MapData, wood: PackedByteArray,
		rng: RandomNumberGenerator) -> void:
	var side := data.size.x
	data.fill_terrain(SimMap.Terrain.GRASS)
	var shape: Dictionary = SHAPE[Type.RIVER]
	var trees := _noise(rng, shape["freq"])
	for y in range(side):
		for x in range(side):
			if trees.get_noise_2d(x, y) > float(shape["wood"]):
				wood[data.index_of(Vector2i(x, y))] = 1

	var axis := _river_axis(rng)
	var half_width: float = maxf(2.5, float(side) * 0.045)
	var bridges := _bridge_positions(side, rng)

	for y in range(side):
		for x in range(side):
			var t := Vector2i(x, y)
			if absf(_river_offset(data, axis, t)) > half_width:
				continue
			var along := _river_along(data, axis, t)
			var on_bridge := false
			for b in bridges:
				if absf(along - b) <= 2.5:          # a 5-tile crossing
					on_bridge = true
					break
			if on_bridge:
				continue
			data.set_terrain(t, SimMap.Terrain.WATER_SHALLOW)
			wood[data.index_of(t)] = 0


## Sand wherever grass meets water (project owner, 2026-08-23: "can we add sand around
## rivers"). Runs over every map type, after the terrain and before anything stands on
## it.
##
## WHAT IT IS REALLY FOR is the hard edge. Terrain is one flat diamond per kind on a
## TileMapLayer, so grass meeting water is a pixel-crisp zigzag of 64x32 diamonds and
## reads as a staircase. There is no blend to reach for -- `TerrainLayer` has no
## transition tiles and nothing for a shader to interpolate between. A sand band does
## not remove the staircase; it replaces ONE high-contrast edge (saturated green
## against saturated blue) with TWO low-contrast ones, and low-contrast staircases are
## much harder for the eye to pick out. It is the cheap eighty per cent.
##
## THE OUTER RING IS RAGGED ON PURPOSE. A uniform two-tile band just draws the same
## staircase twice, parallel, which is arguably worse -- two crisp lines read as a
## deliberate stripe. Dropping tiles from the outer pass at random breaks the second
## edge into something that looks like a coastline instead.
const SHORE_WIDTH := 2
const SHORE_RAGGED := 0.45

static func _paint_shores(data: MapData, wood: PackedByteArray,
		rng: RandomNumberGenerator) -> void:
	var side := data.size.x
	for pass_index in range(SHORE_WIDTH):
		# Collected first and written after, over a SNAPSHOT of the terrain. Writing
		# as we go would let a tile turned to sand this pass seed the next tile in the
		# same pass, and the beach would eat the whole map one row at a time.
		var to_sand: Array[Vector2i] = []
		for y in range(side):
			for x in range(side):
				var t := Vector2i(x, y)
				if data.terrain_at(t) != SimMap.Terrain.GRASS:
					continue
				if not _touches_shore(data, t, pass_index > 0):
					continue
				if pass_index > 0 and rng.randf() < SHORE_RAGGED:
					continue
				to_sand.append(t)
		for t in to_sand:
			data.set_terrain(t, SimMap.Terrain.SAND)
			# No copse on the waterline. `_place_trees` reads this mask, and an oak
			# standing in the surf reads as a bug rather than as scenery -- the palm
			# that would make a beach tree look deliberate is requested and unbaked.
			wood[data.index_of(t)] = 0


## Whether `t` has water beside it -- or, once the first ring is down, sand, which is
## how the band widens outward one ring at a time. All eight neighbours: a diagonal
## touch is a visible corner in this projection, and leaving it out notches the beach.
static func _touches_shore(data: MapData, t: Vector2i, sand_counts: bool) -> bool:
	for dy in range(-1, 2):
		for dx in range(-1, 2):
			if dx == 0 and dy == 0:
				continue
			var n := t + Vector2i(dx, dy)
			if not data.in_bounds(n):
				continue
			var kind := data.terrain_at(n)
			if kind == SimMap.Terrain.WATER_SHALLOW or kind == SimMap.Terrain.WATER_DEEP:
				return true
			if sand_counts and kind == SimMap.Terrain.SAND:
				return true
	return false


static func _paint_desert(data: MapData, wood: PackedByteArray,
		rng: RandomNumberGenerator) -> void:
	var side := data.size.x
	data.fill_terrain(SimMap.Terrain.SAND)
	var oases := _noise(rng, 0.03)
	var scrub := _noise(rng, 0.09)

	for y in range(side):
		for x in range(side):
			var t := Vector2i(x, y)
			var n := oases.get_noise_2d(x, y)
			if n > 0.55:
				data.set_terrain(t, SimMap.Terrain.WATER_SHALLOW)
			elif n > 0.42:
				# A green fringe around each oasis, which is where the little wood a
				# desert has belongs -- the prototype scattered single trees uniformly
				# at random, which reads as noise rather than as an oasis.
				data.set_terrain(t, SimMap.Terrain.GRASS)
				if scrub.get_noise_2d(x, y) > 0.1:
					wood[data.index_of(t)] = 1


static func _paint_forest(data: MapData, wood: PackedByteArray,
		rng: RandomNumberGenerator) -> void:
	var side := data.size.x
	data.fill_terrain(SimMap.Terrain.GRASS)
	var shape: Dictionary = SHAPE[Type.FOREST]
	var canopy := _noise(rng, shape["freq"])
	var lakes := _noise(rng, 0.04)

	for y in range(side):
		for x in range(side):
			var t := Vector2i(x, y)
			if lakes.get_noise_2d(x, y) > float(shape["lake"]):
				data.set_terrain(t, SimMap.Terrain.WATER_SHALLOW)
				continue
			# Broad wood regions with lanes between them, rather than the prototype's
			# copses on grass. See SHAPE for why the frequency is this low.
			if canopy.get_noise_2d(x, y) > float(shape["wood"]):
				wood[data.index_of(t)] = 1


# ── the river's geometry ────────────────────────────────────────────────────

## One of four directions, as (along, perpendicular) integer vectors.
static func _river_axis(rng: RandomNumberGenerator) -> Array:
	match rng.randi_range(0, 3):
		0: return [Vector2(1, 0), Vector2(0, 1)]        # runs east-west
		1: return [Vector2(0, 1), Vector2(1, 0)]        # runs north-south
		2: return [Vector2(1, 1).normalized(), Vector2(1, -1).normalized()]
		_: return [Vector2(1, -1).normalized(), Vector2(1, 1).normalized()]


## Signed perpendicular distance from the river's centre line, in tiles. Its SIGN is
## which bank `t` is on.
static func _river_offset(data: MapData, axis: Array, t: Vector2i) -> float:
	var centre := Vector2(data.size) * 0.5
	return (Vector2(t) - centre).dot(axis[1] as Vector2)


## Distance along the river from its middle, in tiles. Used to place the bridges.
static func _river_along(data: MapData, axis: Array, t: Vector2i) -> float:
	var centre := Vector2(data.size) * 0.5
	return (Vector2(t) - centre).dot(axis[0] as Vector2)


static func _bridge_positions(side: int, rng: RandomNumberGenerator) -> Array[float]:
	var count := rng.randi_range(1, 3)
	var span := float(side) * 0.7          # keep crossings away from the corners
	var out: Array[float] = []
	for i in range(count):
		var fraction := (float(i) + 1.0) / (float(count) + 1.0)
		out.append((fraction - 0.5) * span)
	return out


# ── player starts ───────────────────────────────────────────────────────────

static func _start_positions(data: MapData, type: Type, count: int,
		rng: RandomNumberGenerator) -> Array[Vector2i]:
	if type == Type.RIVER:
		return _river_start_positions(data, count, rng)

	# Equally spread around a ring, with a random rotation so the same player count
	# does not always start in the same corners.
	var side := data.size.x
	var centre := Vector2(side, side) * 0.5
	var radius := float(side) * 0.5 - float(side) * 0.19
	var offset := rng.randf_range(0.0, TAU)
	var out: Array[Vector2i] = []
	for i in range(count):
		var angle := offset + float(i) * TAU / float(count)
		out.append(_clamp_start(data,
				Vector2i(centre + Vector2(cos(angle), sin(angle)) * radius)))
	return out


## Alternating banks, spread along the river's length.
##
## Players alternate sides, so an even count is balanced and an odd one puts the
## extra player on the bank that has fewer -- the owner's rule for 3, 5 and 7.
static func _river_start_positions(data: MapData, count: int,
		rng: RandomNumberGenerator) -> Array[Vector2i]:
	var side := data.size.x
	var centre := Vector2(side, side) * 0.5
	var axis := _river_axis(rng)
	var bank := float(side) * 0.26
	var span := float(side) * 0.55

	# How many land on each bank, so each bank can spread its own players evenly.
	var per_bank := [0, 0]
	for i in range(count):
		per_bank[i % 2] += 1

	var placed := [0, 0]
	var out: Array[Vector2i] = []
	for i in range(count):
		var s := i % 2
		var n: int = per_bank[s]
		var fraction := 0.5 if n == 1 else float(placed[s]) / float(n - 1)
		placed[s] += 1
		var along := (fraction - 0.5) * span
		var side_sign := 1.0 if s == 0 else -1.0
		var pos := centre + (axis[0] as Vector2) * along \
				+ (axis[1] as Vector2) * bank * side_sign
		out.append(_clamp_start(data, Vector2i(pos)))
	return out


## Keep a start far enough inside the map that its clearing and its unit ring fit.
static func _clamp_start(data: MapData, t: Vector2i) -> Vector2i:
	var margin := _base_half_extent() + START_CLEARANCE
	return Vector2i(
			clampi(t.x, margin, data.size.x - 1 - margin),
			clampi(t.y, margin, data.size.y - 1 - margin))


## Half the town centre's footprint, rounded up -- how far its walls reach from the
## start centre. Read from `buildings.json` rather than hardcoded, which is fix (3):
## the prototype reserved 5x5 for a building that is 10x10 in the data.
static func _base_half_extent() -> int:
	var bd: BuildingDef = GameDataRegistry.building(&"building.town_center")
	var footprint := bd.footprint if bd != null else Vector2i(10, 10)
	return int(ceil(float(maxi(footprint.x, footprint.y)) * 0.5))


## Flatten and dry the ground a base needs, and clear the wood off it.
static func _clear_base(data: MapData, wood: PackedByteArray, centre: Vector2i) -> void:
	var reach := _base_half_extent() + START_CLEARANCE
	var ground := data.terrain_at(centre)
	# Keep a desert base on sand and everything else on grass, so a cleared start does
	# not read as a green patch cut out of a desert.
	if ground != SimMap.Terrain.SAND:
		ground = SimMap.Terrain.GRASS
	# ROUNDED, not square. A square clearing draws a hard right-angled patch of grass
	# across a beach or a desert, which reads as a tool mark rather than as a
	# settlement -- visible immediately on the 8-player island preview. The corners are
	# outside the town centre's footprint anyway, so trimming them costs nothing.
	var trim := float(reach) + 1.0
	for y in range(centre.y - reach, centre.y + reach + 1):
		for x in range(centre.x - reach, centre.x + reach + 1):
			var t := Vector2i(x, y)
			var i := data.index_of(t)
			if i < 0:
				continue
			if Vector2(t - centre).length() > trim:
				continue
			data.terrain[i] = ground
			wood[i] = 0


static func _place_base(data: MapData, claimed: Dictionary, player: int,
		centre: Vector2i, type: Type, rng: RandomNumberGenerator) -> void:
	var bd: BuildingDef = GameDataRegistry.building(&"building.town_center")
	var footprint := bd.footprint if bd != null else Vector2i(10, 10)
	var origin := centre - footprint / 2
	data.add_entity(&"building.town_center", player, origin)
	for t in MapData.footprint_rect_of(data.entities[data.entities.size() - 1]):
		claimed[t] = true

	# Villagers and the scout on a ring outside the walls, at every other position so
	# no two stand adjacent. `unit.scout_cavalry` -- fix (4): `unit.scout` does not
	# exist in units.json.
	var ring := _ring_tiles(centre, UNIT_RING_RADIUS)
	var wanted := MapGen.STARTING_VILLAGERS + 1
	var step := maxi(2, ring.size() / maxi(1, wanted))
	var placed := 0
	var i := 0
	while placed < wanted and i < ring.size():
		var t: Vector2i = ring[i]
		i += step
		if not data.is_ground_passable(t) or claimed.has(t):
			continue
		claimed[t] = true
		data.add_entity(&"unit.scout_cavalry" if placed == wanted - 1
				else &"unit.villager", player, t)
		placed += 1

	# The guaranteed opening. Every start gets stone, gold, food and wood within
	# walking distance whatever the terrain did -- see START_WOOD_COUNT's header for
	# what leaving this to the noise cost.
	_place_vein(data, claimed, centre, &"res.stone", STONE_TILES, rng)
	_place_vein(data, claimed, centre, &"res.gold_mine", GOLD_TILES, rng)
	_place_scatter(data, claimed, centre, &"res.berry_bush", START_FOOD_COUNT,
			START_WOOD_MIN, START_WOOD_MAX, rng)
	# WOOD IS PER TYPE since 2026-08-30, for the archipelago's sake -- see `CONTENT`.
	# Everything else takes the constants and generates exactly the opening it always did.
	_place_scatter(data, claimed, centre, &"res.tree",
			_content(type, &"start_wood", START_WOOD_COUNT),
			START_WOOD_MIN, _content(type, &"start_wood_max", START_WOOD_MAX), rng)

	# Wildlife. Sheep and deer are nodes harvested where they stand; the wolf is a
	# gaia UNIT that comes at you (4.13), which is why it goes through a different
	# placer -- `_place_scatter` asks the resource table and a unit is not in it.
	# Sheep are units since 6.5 -- a thing you walk home has to be able to walk.
	#
	# COUNTS COME THROUGH `_content`, which answers the constant unless the type says
	# otherwise (see CONTENT). A herd count of ZERO has to be a legal answer and is: the
	# archipelago has no deer, because seven of them on a one-base island is most of an
	# opening's food standing still.
	_place_unit_herds(data, claimed, centre, &"unit.sheep",
			_content(type, &"sheep_herds", SHEEP_HERDS), SHEEP_PER_HERD,
			SHEEP_MIN, SHEEP_MAX, rng)
	# DEER ARE UNITS since 6.1b -- they wander and bolt, which nodes cannot -- so the
	# herd goes through the gaia-unit placer. The shape of the herd is unchanged.
	_place_unit_herds(data, claimed, centre, &"unit.deer",
			_content(type, &"deer_herds", DEER_HERDS), DEER_PER_HERD,
			DEER_MIN, DEER_MAX, rng)
	# Fish, wherever there is shallow water in reach. Every map type gets the call and
	# the ones with no water near this start simply place none.
	_place_water_scatter(data, claimed, centre, &"res.fish",
			_content(type, &"fish", FISH_COUNT), FISH_MIN, FISH_MAX, rng)

	# THE MAP TYPE PICKS THE PREDATOR -- see PREDATORS. One species per map, so a
	# player learns one animal's behaviour per match rather than three at once.
	var predator: Dictionary = PREDATORS.get(type, {})
	if not predator.is_empty():
		_place_gaia_units(data, claimed, centre, predator["def"], int(predator["count"]),
				int(predator["min"]), int(predator["max"]), rng)


## One per-type content number, or `fallback` for the types that take the standard
## opening. See `CONTENT` for why this is a table of differences.
static func _content(type: Type, key: StringName, fallback: int) -> int:
	return int((CONTENT.get(type, {}) as Dictionary).get(key, fallback))


## Tiles at exactly Chebyshev `radius` from `centre`, clockwise from the north-west
## corner. A fixed order, because two clients placing a start must agree.
static func _ring_tiles(centre: Vector2i, radius: int) -> Array[Vector2i]:
	var out: Array[Vector2i] = []
	for x in range(centre.x - radius, centre.x + radius + 1):
		out.append(Vector2i(x, centre.y - radius))
	for y in range(centre.y - radius + 1, centre.y + radius + 1):
		out.append(Vector2i(centre.x + radius, y))
	for x in range(centre.x + radius - 1, centre.x - radius - 1, -1):
		out.append(Vector2i(x, centre.y + radius))
	for y in range(centre.y + radius - 1, centre.y - radius, -1):
		out.append(Vector2i(centre.x - radius, y))
	return out


## Scatter `count` nodes of `def_id` in a ring between `min_r` and `max_r` tiles of
## `centre`, skipping anything claimed or unwalkable.
##
## Angles are stepped evenly with a random rotation rather than drawn independently,
## so a cluster spreads around the base instead of clumping on one side -- and gives
## up after a bounded number of tries rather than searching forever for room.
static func _place_scatter(data: MapData, claimed: Dictionary, centre: Vector2i,
		def_id: StringName, count: int, min_r: int, max_r: int,
		rng: RandomNumberGenerator) -> void:
	var rd: ResourceDef = GameDataRegistry.resource_def(def_id)
	if rd == null:
		return
	var offset := rng.randf_range(0.0, TAU)
	var placed := 0
	var attempts := 0
	while placed < count and attempts < count * 12:
		# Sweep the ring rather than re-rolling the same angle: `attempts` advances the
		# angle, so a blocked direction is stepped past instead of retried.
		var angle := offset + float(attempts) * TAU / float(maxi(1, count * 3))
		var radius := rng.randf_range(float(min_r), float(max_r))
		attempts += 1
		var tile := centre + Vector2i(Vector2(cos(angle), sin(angle)) * radius)
		var size_class := rng.randi_range(0, maxi(0, rd.amounts.size() - 1))
		var footprint := rd.footprint_for_size(size_class)

		var free := true
		for y in range(tile.y, tile.y + footprint.y):
			for x in range(tile.x, tile.x + footprint.x):
				var t := Vector2i(x, y)
				if claimed.has(t) or not data.is_ground_passable(t):
					free = false
					break
			if not free:
				break
		if not free:
			continue

		data.add_entity(def_id, 0, tile, size_class)
		for t in MapData.footprint_rect_of(data.entities[data.entities.size() - 1]):
			claimed[t] = true
		placed += 1


## `herds` clumps of `per_herd` animals, each clump anchored somewhere in the ring
## between `min_r` and `max_r` of the base.
##
## TWO STAGES, and the reason is that a herd is a shape rather than a count. Scattering
## `herds * per_herd` animals over the whole ring in one pass gives an even sprinkle --
## six sheep spread evenly around a base is not two flocks, and the player reads it as
## noise. Anchoring first and clumping second is `_place_trees`'s copse argument applied
## to livestock, and for the same reason: the grouping is the thing you can see.
static func _place_herds(data: MapData, claimed: Dictionary, centre: Vector2i,
		def_id: StringName, herds: int, per_herd: int, min_r: int, max_r: int,
		rng: RandomNumberGenerator) -> void:
	for i in range(herds):
		# Anchors stepped evenly apart with a random rotation, so two herds land on
		# opposite sides of the base rather than on top of each other -- the same
		# even-sweep trick `_place_scatter` uses within one cluster.
		var base_angle := rng.randf_range(0.0, TAU) + float(i) * TAU / float(maxi(1, herds))
		# RETRIED, because one bad anchor loses a WHOLE HERD and that is visible. The
		# first version took whatever the angle gave it, and a seed that put a deer
		# anchor in a river dropped seven deer and left the map short a food source
		# nobody could see was missing. Each retry nudges the angle rather than
		# re-rolling it, so the herd stays on the side of the base it was meant for.
		for attempt in range(ANCHOR_ATTEMPTS):
			var angle := base_angle + float(attempt) * 0.4
			var radius := rng.randf_range(float(min_r), float(max_r))
			var anchor := centre + Vector2i(Vector2(cos(angle), sin(angle)) * radius)
			if not data.in_bounds(anchor) or not data.is_ground_passable(anchor):
				continue
			_place_scatter(data, claimed, anchor, def_id, per_herd, 0, HERD_SPREAD, rng)
			break


## `_place_scatter` for nodes that live in SHALLOW WATER -- the fish, and nothing else.
##
## A SEPARATE SWEEP RATHER THAN A FLAG ON `_place_scatter`, because the two differ in
## the one line that matters and agree nowhere else: this one wants water and cannot use
## `is_ground_passable`, which is land-only by definition. Sharing them would have meant
## a domain parameter threaded through a function whose every other caller is a tree.
##
## Sweeps a wide arc rather than stepping evenly: water is not distributed around a base
## the way trees are -- a river cuts one side of it and an island rims the whole thing --
## so the angle has to be free to wander until it finds some.
static func _place_water_scatter(data: MapData, claimed: Dictionary, centre: Vector2i,
		def_id: StringName, count: int, min_r: int, max_r: int,
		rng: RandomNumberGenerator) -> void:
	if GameDataRegistry.resource_def(def_id) == null:
		return
	var offset := rng.randf_range(0.0, TAU)
	var placed := 0
	var attempts := 0
	# A bigger budget than the land placers get, for the reason above: most of a ring
	# around a river start is dry, and giving up early would leave the water empty.
	while placed < count and attempts < count * 60:
		var angle := offset + float(attempts) * 0.11
		var radius := rng.randf_range(float(min_r), float(max_r))
		attempts += 1
		var tile := centre + Vector2i(Vector2(cos(angle), sin(angle)) * radius)
		if not data.in_bounds(tile) or claimed.has(tile):
			continue
		if data.terrain_at(tile) != SimMap.Terrain.WATER_SHALLOW:
			continue
		claimed[tile] = true
		data.add_entity(def_id, 0, tile)
		placed += 1


## `_place_herds` for gaia UNITS. Same anchor-then-clump shape, same retry, different
## placer at the bottom -- because a deer is a unit and `_place_scatter` reads the
## resource table and bails on anything that is not a node.
static func _place_unit_herds(data: MapData, claimed: Dictionary, centre: Vector2i,
		def_id: StringName, herds: int, per_herd: int, min_r: int, max_r: int,
		rng: RandomNumberGenerator) -> void:
	for i in range(herds):
		var base_angle := rng.randf_range(0.0, TAU) + float(i) * TAU / float(maxi(1, herds))
		for attempt in range(ANCHOR_ATTEMPTS):
			var angle := base_angle + float(attempt) * 0.4
			var radius := rng.randf_range(float(min_r), float(max_r))
			var anchor := centre + Vector2i(Vector2(cos(angle), sin(angle)) * radius)
			if not data.in_bounds(anchor) or not data.is_ground_passable(anchor):
				continue
			_place_gaia_units(data, claimed, anchor, def_id, per_herd, 0, HERD_SPREAD, rng)
			break


## Gaia units -- the predators, and the deer. Deliberately NOT `_place_scatter`,
## which reads `GameDataRegistry.resource_def` and bails on anything that is not a node.
##
## Owner 0 is passed as the `player` INDEX, which `MapGen.build_from` maps straight to
## owner 0 rather than to a seat: index 0 means gaia there, and every animal on the map
## already goes in that way.
static func _place_gaia_units(data: MapData, claimed: Dictionary, centre: Vector2i,
		def_id: StringName, count: int, min_r: int, max_r: int,
		rng: RandomNumberGenerator) -> void:
	if GameDataRegistry.unit(def_id) == null:
		return
	var offset := rng.randf_range(0.0, TAU)
	var placed := 0
	var attempts := 0
	while placed < count and attempts < count * 12:
		var angle := offset + float(attempts) * TAU / float(maxi(1, count * 3))
		var radius := rng.randf_range(float(min_r), float(max_r))
		attempts += 1
		var tile := centre + Vector2i(Vector2(cos(angle), sin(angle)) * radius)
		if claimed.has(tile) or not data.is_ground_passable(tile):
			continue
		# Claimed even though a unit is never written into the occupancy grid, so two
		# wolves cannot be handed the same tile and nothing else is placed under them.
		claimed[tile] = true
		data.add_entity(def_id, 0, tile)
		placed += 1


## One dragon nest and one mother, as near the middle of the map as the ground and the
## clearance allow (PLAN.md 13.2). See `NEST_DEF` for why this is the whole of "one dragon
## per map" and why it sits where it does in `_generate_once`.
##
## **BEST-EFFORT, LIKE EVERY PLACER HERE, AND THE ARCHIPELAGO IS THE CASE THAT MISSES.**
## Its middle is open ocean and its only land is an island per player -- an island of radius
## `ISLAND_RADIUS` centred on a start, so every tile of it is within 26 of that start and a
## nest needing `nest_start_clearance()` (24) plus its own five-tile half-extent cannot fit
## on dry land anywhere. It therefore gets no nest, and that falls out of the arithmetic
## rather than out of a special case: nothing here mentions the type. **Whether a naval map
## should get a nest islet of its own is a design question and not a bug** -- an air unit
## crossing water a land army cannot is a good fight, and it is the owner's call.
##
## A missing def is also survivable and is checked first, exactly as `_place_scatter` checks
## for its `ResourceDef`: a project without the nest declared generates the map it always
## did rather than crashing.
static func _place_nest(data: MapData, claimed: Dictionary, rng: RandomNumberGenerator) -> void:
	var bd: BuildingDef = GameDataRegistry.building(NEST_DEF)
	if bd == null:
		return
	# ⚠️ **PREFERRED, THEN ACCEPTED, AND THE TWO PASSES ARE WHAT THE AI TAUGHT THIS
	# FUNCTION.** The first also keeps her reach off the straight lines between starts (see
	# `_off_every_road`); the second drops that and takes the most central site left. A map
	# with no nest is worse than a nest on somebody's road.
	if _try_nest(data, claimed, rng, true):
		return
	_try_nest(data, claimed, rng, false)


## One search for a nest site. True if one was found and the nest and mother were placed.
static func _try_nest(data: MapData, claimed: Dictionary, rng: RandomNumberGenerator,
		off_road: bool) -> bool:
	var bd: BuildingDef = GameDataRegistry.building(NEST_DEF)
	var footprint := bd.footprint
	var half := int(ceil(float(maxi(footprint.x, footprint.y)) * 0.5))
	var clearance := float(nest_start_clearance())
	var middle := Vector2i(data.size.x / 2, data.size.y / 2)
	var protected := _opening_tiles(data)
	var reach := nest_guard_radius()
	var road_keep_out := float(reach + NEST_CLEARANCE_SLACK) if off_road else 0.0

	# OUTWARD FROM THE CENTRE, ring by ring, so the site is the most central one that
	# qualifies. `max_radius` is a fraction of the board rather than a constant, because
	# what the search has to cross is a feature of the MAP: a river map's two starts both
	# sit at the river's midpoint, so a nest has to walk ~20 tiles ALONG the water on a
	# 96-tile board before it is far enough from either of them -- and a fixed number that
	# covered that would be most of the way across an eight-player board.
	for radius in range(0, data.size.x / 3 + 1):
		# Radius 0 is the centre tile itself; `_ring_tiles` would hand back four copies of
		# it, since its four edge walks all degenerate onto the same tile.
		var ring: Array[Vector2i] = [middle]
		if radius > 0:
			ring = _ring_tiles(middle, radius)
		# ROTATED BY THE SEED. `_ring_tiles` starts at the north-west corner and runs
		# clockwise, so taking the first fit would put every river map's nest on the same
		# side of the water. The rotation is a draw from the seeded rng like every other
		# angle in this file, so it is still identical on two machines.
		var start := rng.randi_range(0, ring.size() - 1)
		for n in range(ring.size()):
			var centre: Vector2i = ring[(start + n) % ring.size()]
			var origin := centre - footprint / 2
			# CHEAPEST TEST FIRST, and on the archipelago that ordering is the difference
			# between a fast miss and a slow one: `_nest_fits` gives up on its first tile of
			# sea, and the guard sweep below is 441 lookups that never need doing.
			if not _clear_of_every_start(data, centre, clearance):
				continue
			if not _nearer_the_middle(data, centre, middle):
				continue
			if not _off_every_road(data, centre, road_keep_out):
				continue
			if not _nest_fits(data, claimed, origin, footprint):
				continue
			if not _out_of_reach(protected, centre, reach):
				continue
			data.add_entity(NEST_DEF, 0, origin)
			for t in MapData.footprint_rect_of(data.entities[data.entities.size() - 1]):
				claimed[t] = true
			# HER FIRST, THEN THE CLEARING, and the order is forced: she stands one tile
			# off the footprint, which is inside her own reach, so claiming the circle
			# first would leave her nowhere to be put.
			_place_guardian(data, claimed, centre, half)
			_claim_her_reach(claimed, centre, reach)
			return true
	return false


## Whether a nest standing at `origin` covers nothing but free, walkable ground.
##
## WALKABLE, even though the nest itself does not block movement (`buildings.json`: it is a
## henge of stones you walk through). The requirement is not about the nest -- it is that
## the thing everybody has to come and fight over stands on ground everybody can reach, and
## half a nest in a lake would be a POI you cannot lay siege to.
static func _nest_fits(data: MapData, claimed: Dictionary, origin: Vector2i,
		footprint: Vector2i) -> bool:
	for y in range(origin.y, origin.y + footprint.y):
		for x in range(origin.x, origin.x + footprint.x):
			var t := Vector2i(x, y)
			if claimed.has(t) or not data.is_ground_passable(t):
				return false
	return true


## Whether `centre` is at least `clearance` tiles from every start.
##
## EUCLIDEAN, matching `_sprinkle_trees`' own keep-out test rather than the Chebyshev the
## rings are built on -- what is being asked is "how far is the walk", and a diagonal
## Chebyshev radius would let a nest sit 1.4x nearer a start on the diagonal than on the
## axis for the same number.
static func _clear_of_every_start(data: MapData, centre: Vector2i, clearance: float) -> bool:
	for start in data.starts:
		if Vector2(centre - start).length() < clearance:
			return false
	return true


## Every tile of the guaranteed opening: what a player owns, and every resource node they
## will send somebody to stand on.
##
## ⚠️ **THIS IS THE RULE `nest_start_clearance()` ALONE COULD NOT EXPRESS, AND THE AI FOUND
## IT (2026-09-04).** A distance from the START protects the base and the ring the villagers
## stand on. It does not protect the ECONOMY, because `_place_vein` walks outward from 9
## tiles off the base for up to `VEIN_MAX_STEPS` and a 35-tile stone vein can wander a long
## way further -- so a start whose ore happened to run toward the middle put a working tile
## inside the dragon's reach. She then ate whoever was sent to mine it, over and over.
##
## `test_ai_playtest` is what reported it, and it reported it as an ECONOMY failure: the
## bot finished 9,000 ticks on 3 food, having never saved the 500 an age costs, holding
## three villagers of the eight it had trained. Nothing said "a dragon killed them"; the
## symptom was a bot that could not afford to advance.
##
## **GAIA IS DELIBERATELY NOT IN HERE.** A deer herd or a wolf inside her circle is nobody's
## problem -- she does not hunt gaia (`Diplomacy` sends owner 0 looking at owner 0 home as
## "not an enemy") -- and counting them would push the nest away from the middle for no
## gain. What is kept is precisely what a player has a reason to walk to.
static func _opening_tiles(data: MapData) -> Dictionary:
	var out: Dictionary = {}
	for e in data.entities:
		var owned := int(e.get("player", 0)) > 0
		var workable := GameDataRegistry.resource_def(e.get("def_id", &"")) != null
		if not owned and not workable:
			continue
		for t in MapData.footprint_rect_of(e):
			out[t] = true
	return out


## Reserve every tile the mother answers for, so nothing is grown inside it afterwards.
##
## ⚠️ **`_out_of_reach` GUARDS THE GROUND THAT IS ALREADY TAKEN; THIS GUARDS THE GROUND
## THAT IS ABOUT TO BE.** The nest goes in before both tree passes, so a check against
## `data.entities` at that moment cannot see a single copse -- and a copse eight tiles from
## the nest is precisely what killed the AI's villagers: a *reason* to walk into her reach,
## which is worse than a route that happens to pass through it.
##
## Through `claimed`, which is the mechanism this file already uses for "nothing goes here",
## so `_place_trees` and `_sprinkle_trees` need no idea a dragon exists. The visible result
## is a bare clearing round the henge -- correct on a forest map for the same reason it is
## correct anywhere: nothing grows where a dragon lives.
static func _claim_her_reach(claimed: Dictionary, centre: Vector2i, reach: int) -> void:
	for dy in range(-reach, reach + 1):
		for dx in range(-reach, reach + 1):
			claimed[centre + Vector2i(dx, dy)] = true


## Whether nothing in `tiles` is within `reach` tiles of `centre`.
##
## CHEBYSHEV, because that is the metric the thing being modelled uses: `_nearest_prey`
## measures its aggro radius with `CombatSystem.tile_gap`, and a Euclidean test here would
## leave the diagonal corners of her real reach unprotected.
static func _out_of_reach(tiles: Dictionary, centre: Vector2i, reach: int) -> bool:
	for dy in range(-reach, reach + 1):
		for dx in range(-reach, reach + 1):
			if tiles.has(centre + Vector2i(dx, dy)):
				return false
	return true


## Whether a nest here would still read as the middle of the map: no further from the
## centre of the board than it is from the nearest start.
##
## ⚠️ **THIS IS WHAT STOPS "OFF THE ROAD" TURNING INTO "IN SOMEBODY'S BACK GARDEN", and
## without it the road rule below fails in the worst possible way -- by SUCCEEDING a long
## way out.** Starts sit on a ring, so on four or eight players there is a chord between
## every pair and the chords crisscross the whole middle; the first ground clear of all of
## them is the board's own corner. Measured before this existed: nests 45 to 82 tiles
## off-centre with the nearest start at 24 tiles, which is the clearance floor. The rule
## looked like it was working and the map was worse than if it had not.
##
## **A COMPARISON RATHER THAN A FRACTION**, and that is deliberate. Any "no further than a
## quarter of the board" number has to be re-justified for every board size -- and would
## have been wrong anyway, because the rings are Chebyshev and a diagonal cap of 32 tiles is
## 45 tiles of real distance. *Nearer the middle than the nearest player* needs no
## calibration, means exactly what the design says ("a contested midpoint"), and is true on
## every board from 96 to 192.
static func _nearer_the_middle(data: MapData, centre: Vector2i, middle: Vector2i) -> bool:
	var from_middle := Vector2(centre - middle).length()
	for start in data.starts:
		if Vector2(centre - start).length() < from_middle:
			return false
	return true


## Whether `centre` is at least `keep_out` tiles off the straight line between every pair
## of starts. Always true for a `keep_out` of 0, which is the second pass.
##
## ⚠️ **THE MAP CENTRE IS ON EVERY ROAD, AND THAT IS GEOMETRY RATHER THAN BAD LUCK.**
## `_start_positions` puts starts evenly around a ring, so on a two-player map they are
## diametrically opposite and *the line between them passes through the middle of the board*.
## A POI at the centre is therefore not "equidistant and contested", it is **parked on the
## only road** -- and `MapValidator` guarantees that road exists.
##
## **`test_ai_playtest` is what found this, and it found it as an economy failure.** The bot
## worked out its opening, picked the next nearest wood -- 60 tiles away, across the map --
## and walked villager after villager from (41, 18) to (65, 78) past a nest at (48, 48). That
## route passes **4.6 tiles** from the nest's middle, so every one of them was one-shot by a
## 30-damage flyer on the way. The bot finished 9,000 ticks on 3 food with 4 units left,
## having trained eight; nothing in the log said "dragon", only that it could never afford
## an age. **This is PLAN.md §14's declared ceiling being reached by a new hazard rather
## than a new defect** -- the AI has no condition that can see danger, so it will feed the
## same route forever.
##
## **AND NO TUNING OF HER REACH FIXES IT, WHICH IS WHY THIS IS A PLACEMENT RULE.** Measured
## against that route: an aggro radius of 7, 6 or 5 still catches it at 4.6 tiles, and 4
## clears it by half a tile. Making the nest block movement makes it worse, not better --
## A* then hugs the footprint, which is nearer her middle than cutting the corner was. The
## only variable with any room in it is *where the nest is*.
##
## `keep_out` is her reach plus `NEST_CLEARANCE_SLACK`, because a real route is not a
## straight line: it bends around woods and lakes, and the slack is what that bending
## may cost. Seventeen tiles off the mid-line of a 96-tile board is still equidistant from
## both starts and still the middle of the map to look at.
static func _off_every_road(data: MapData, centre: Vector2i, keep_out: float) -> bool:
	if keep_out <= 0.0:
		return true
	var here := Vector2(centre)
	for i in range(data.starts.size()):
		for j in range(i + 1, data.starts.size()):
			if _gap_to_segment(here, Vector2(data.starts[i]), Vector2(data.starts[j])) < keep_out:
				return false
	return true


## Distance from `p` to the segment `a`-`b`. The road, not the infinite line: two starts on
## the far side of the board from each other say nothing about the ground beyond either of
## them, and using the line would rule out the whole diameter rather than the part between.
static func _gap_to_segment(p: Vector2, a: Vector2, b: Vector2) -> float:
	var along := b - a
	var length_squared := along.length_squared()
	if length_squared <= 0.0:
		return p.distance_to(a)          # two starts on one tile; nothing to divide by
	var t := clampf((p - a).dot(along) / length_squared, 0.0, 1.0)
	return p.distance_to(a + along * t)


## The mother, one tile off the nest's footprint (PLAN.md 13.2). Gaia's, like every animal.
##
## SHE IS NOT REQUIRED TO STAND ON LAND, and that is not laziness: she is `domain: air`, so
## `SimMap` lets her over water, forest and rock alike, and a nest whose north side happens
## to be a lake would otherwise leave the map's one dragon unplaced over a technicality
## about ground she never touches. What she does need is a tile nothing else has claimed.
##
## The ring widens if the first is full, because the nest's own surroundings are the one
## place on the map where something else (a base's outer resource ring, a neighbouring
## start's trees) may already be standing.
static func _place_guardian(data: MapData, claimed: Dictionary, centre: Vector2i,
		half: int) -> void:
	if GameDataRegistry.unit(NEST_GUARDIAN_DEF) == null:
		return
	for out in range(NEST_GUARDIAN_RING, NEST_GUARDIAN_RING + 4):
		for t in _ring_tiles(centre, half + out):
			if not data.in_bounds(t) or claimed.has(t):
				continue
			claimed[t] = true
			data.add_entity(NEST_GUARDIAN_DEF, 0, t)
			return


## Walk a vein of `def_id` outward from `VEIN_DISTANCE` tiles off the base, placing
## nodes until `target_tiles` tiles are claimed or the walk runs out of steps.
##
## The step cap is fix (8): the prototype counted only tiles it actually wrote, so a
## vein that wandered off the map or back over itself never reached its target and
## looped. It also had no guard against drawing over a town centre; `claimed` is that
## guard, and it is shared across every base and vein on the map.
static func _place_vein(data: MapData, claimed: Dictionary, centre: Vector2i,
		def_id: StringName, target_tiles: int, rng: RandomNumberGenerator) -> void:
	var rd: ResourceDef = GameDataRegistry.resource_def(def_id)
	if rd == null:
		return

	var angle := rng.randf_range(0.0, TAU)
	var cursor := centre + Vector2i(Vector2(cos(angle), sin(angle)) * float(VEIN_DISTANCE))
	var drift := Vector2i(rng.randi_range(-1, 1), rng.randi_range(-1, 1))
	if drift == Vector2i.ZERO:
		drift = Vector2i(1, 0)          # a zero drift never moves and never terminates

	var claimed_here := 0
	var steps := 0
	while claimed_here < target_tiles and steps < VEIN_MAX_STEPS:
		steps += 1
		if rng.randf() < 0.25:
			drift = Vector2i(rng.randi_range(-1, 1), rng.randi_range(-1, 1))
			if drift == Vector2i.ZERO:
				drift = Vector2i(0, 1)
		cursor += drift

		var size_class := rng.randi_range(0, maxi(0, rd.amounts.size() - 1))
		var footprint := rd.footprint_for_size(size_class)
		var free := true
		for y in range(cursor.y, cursor.y + footprint.y):
			for x in range(cursor.x, cursor.x + footprint.x):
				var t := Vector2i(x, y)
				if claimed.has(t) or not data.is_ground_passable(t):
					free = false
					break
			if not free:
				break
		if not free:
			continue

		data.add_entity(def_id, 0, cursor, size_class)
		for t in MapData.footprint_rect_of(data.entities[data.entities.size() - 1]):
			claimed[t] = true
			claimed_here += 1


## The copse lattice for a board of this size: the type's own `spacing`, widened so that
## a BIGGER MAP GETS ROUGHLY THE SAME NUMBER OF TREES rather than proportionally more.
##
## **THE TREE COUNT IS A BUDGET, AND IT IS SHARED BY EVERY PLAYER ON THE BOARD.** Density
## per unit area is the obvious way to write this and it is wrong at the top end: the
## 2026-08-28 density work was measured at 2 players and shipped for an afternoon with a
## flat spacing, which put **5,655 entities and a 786 KB map** on the 8-player 192x192
## forest -- four times the area, four times everything, on the map most likely to be
## running eight AIs at once. Scaling the lattice with the square root of the area holds
## it near 1,300 trees on every board: 6 at 96x96, 8 at 128x128, 12 at 192x192.
##
## What that trades away is honest and worth stating: **a big forest map is thinner than
## a small one**. The alternative is a map whose cost is unbounded in the one direction
## the player controls, and the wood still reads as closed canopy at 12 -- the copses are
## 5 tiles across and the sprites are wider than their tiles.
##
## Scaled by the SIDE rather than the area, which is the same thing said in integers: a
## board twice as wide has four times the area, so doubling the lattice pitch holds the
## count. Reference is the smallest board the game offers, `side_for(MIN_PLAYERS)` = 96,
## which is what the density was tuned against.
##
## Integer throughout and a pure function of the size, so two hosts generating the same
## map cannot disagree about it.
static func tree_spacing(shape: Dictionary, size: Vector2i) -> int:
	return spacing_for(int(shape.get("spacing", TREE_CLUMP_SPACING)), size)


## The scaling above with the shape lookup taken off the front, so the SPRINKLE lattice
## (2026-08-30) widens on a big board by the same rule the copse lattice does. Split out
## rather than given a second copy: the whole argument in `tree_spacing`'s header is that
## a lattice must scale with the SIDE or the count is unbounded in the one direction the
## player controls, and that argument applies to any lattice, not to copses in particular.
static func spacing_for(base: int, size: Vector2i) -> int:
	var reference := maxi(1, side_for(MIN_PLAYERS))
	return maxi(base, base * maxi(size.x, size.y) / reference)


## A ROAD BETWEEN EVERY PAIR OF NEIGHBOURING STARTS, cleared out of the wood mask
## (project owner, 2026-08-28). Forest only -- see `LANE_HALF_WIDTH`.
##
## AROUND THE RING AND NOT BETWEEN ALL PAIRS. `_start_positions` spreads starts evenly
## around a ring, so joining each to the next closes a loop that reaches everybody: eight
## players cost eight lanes rather than twenty-eight, and the map does not end up as a
## spider's web with more road than wood in it. Two players are a special case of the
## same loop -- start 0 to start 1 and back, which is one road drawn twice.
##
## Bresenham-free: it walks the line in floating steps and stamps a square either side,
## which is enough for a corridor whose edges are meant to look chewed rather than
## surveyed. The float never reaches sim state -- this writes into a mask that decides
## where trees are placed at GENERATION time, and the map that comes out is bytes
## (2.4c's rule: the content is authoritative, not how it came to be).
## RETURNS THE ROAD, as a set of tiles, and that is not bookkeeping for its own sake.
##
## Clearing the wood MASK is enough to keep copses off the road, because `_place_trees`
## reads the mask. `_sprinkle_trees` (2026-08-30) deliberately does NOT read it -- that is
## the whole of what makes it a sprinkle over open ground -- so it would have put single
## trees straight down the middle of the one corridor this function exists to keep clear,
## and `test_there_is_a_clear_road_between_the_players` is the only thing that would have
## said so. The set is what the sprinkle avoids.
static func _clear_lanes(data: MapData, wood: PackedByteArray) -> Dictionary:
	var road: Dictionary = {}
	var starts := data.starts
	if starts.size() < 2:
		return road
	for i in range(starts.size()):
		var a := starts[i]
		var b := starts[(i + 1) % starts.size()]
		if a == b:
			continue
		var span := maxi(1, int(Vector2(b - a).length()))
		for s in range(span + 1):
			var at := Vector2(a).lerp(Vector2(b), float(s) / float(span))
			var centre := Vector2i(roundi(at.x), roundi(at.y))
			for dy in range(-LANE_HALF_WIDTH, LANE_HALF_WIDTH + 1):
				for dx in range(-LANE_HALF_WIDTH, LANE_HALF_WIDTH + 1):
					var t := centre + Vector2i(dx, dy)
					var index := data.index_of(t)
					if index >= 0:
						wood[index] = 0
						road[t] = true
	return road


## Copses on anchors over the wood mask, skipping anything already claimed.
##
## Everything random here comes from a HASH OF THE ANCHOR rather than from the rng --
## the jitter, the clump's rotation and each tree's size class. That makes the whole
## wood a pure function of the mask, so it cannot depend on the order tiles are visited
## (PLAN.md 7.1) and a tree keeps its size if this loop is ever reordered. It is also
## what breaks the lattice up: without the jitter the anchors are visibly on a grid.
static func _place_trees(data: MapData, wood: PackedByteArray,
		claimed: Dictionary, spacing := TREE_CLUMP_SPACING,
		clump := 5) -> void:
	var rd: ResourceDef = GameDataRegistry.resource_def(&"res.tree")
	var classes := maxi(1, rd.amounts.size() if rd != null else 1)
	var shape_count := clampi(clump, 1, TREE_CLUMP_SHAPE.size())

	for ay in range(0, data.size.y, spacing):
		for ax in range(0, data.size.x, spacing):
			var anchor := Vector2i(ax, ay)
			var i := data.index_of(anchor)
			if i < 0 or wood[i] == 0:
				continue

			var h := absi(ax * 73856093 ^ ay * 19349663)
			# Jitter by up to +/-2 tiles, so no two copses sit on the same grid.
			var jittered := anchor + Vector2i(h % 5 - 2, (h / 5) % 5 - 2)
			# Rotate which tiles of the shape are used, so the copses are not clones.
			var rotate := (h / 25) % shape_count

			for n in range(shape_count):
				var offset: Vector2i = TREE_CLUMP_SHAPE[(n + rotate) % shape_count]
				var t: Vector2i = jittered + offset
				var ti := data.index_of(t)
				# Still inside the wood: a clump that straddles a clearing edge stops
				# at it rather than spilling trees onto open ground.
				if ti < 0 or wood[ti] == 0 or claimed.has(t):
					continue
				if not data.is_ground_passable(t):
					continue
				claimed[t] = true
				data.add_entity(&"res.tree", 0, t,
						absi(t.x * 40503 ^ t.y * 12289) % classes)


## SINGLE TREES OVER OPEN GROUND, off the wood mask entirely. See `SPRINKLE_SPACING` for
## why this is a second pass rather than a looser threshold on the first.
##
## Deterministic the same way `_place_trees` is, and for the same reason: everything
## random here is a HASH OF THE ANCHOR rather than a draw from the rng, so the result is
## a pure function of the board and cannot depend on the order tiles are visited (PLAN.md
## 7.1). It also means adding this pass does not shift the rng stream, so **every existing
## seed still generates the terrain, veins, herds and copses it always did** -- the
## sprinkle is added on top rather than displacing what was there.
##
## The size class uses the SAME hash as a copse tree (`t.x * 40503 ^ t.y * 12289`), so a
## sprinkled tree and a wood tree standing on the same tile would be the same tree. That
## is deliberate: the two passes differ in WHERE they place, never in what.
static func _sprinkle_trees(data: MapData, claimed: Dictionary,
		spacing := SPRINKLE_SPACING, road: Dictionary = {}) -> void:
	var rd: ResourceDef = GameDataRegistry.resource_def(&"res.tree")
	var classes := maxi(1, rd.amounts.size() if rd != null else 1)
	var keep_out := _base_half_extent() + START_CLEARANCE + SPRINKLE_START_CLEARANCE

	for ay in range(0, data.size.y, spacing):
		for ax in range(0, data.size.x, spacing):
			var h := absi(ax * 83492791 ^ ay * 29996224)
			# Jitter by up to +/-4 tiles, wider than a copse's +/-2 because a lone tree on
			# a visible lattice is an orchard even more plainly than a clump is -- there is
			# no blob shape to disguise the grid.
			var t := Vector2i(ax + h % 9 - 4, ay + (h / 9) % 9 - 4)
			if data.index_of(t) < 0 or claimed.has(t):
				continue
			# THE FOREST'S ROAD, which this pass cannot see any other way: `_clear_lanes`
			# keeps copses off it by clearing the wood MASK, and reading that mask is
			# exactly what a sprinkle over open ground must not do. Empty on every other
			# type, which have no lanes to respect.
			if road.has(t):
				continue
			if not data.is_ground_passable(t):
				continue
			# CLEAR OF EVERY BASE, not just of what is standing in one. `claimed` holds the
			# town centre's tiles and the starting units', and nothing else in the
			# clearing -- so without this a tree lands in the gap between the wall and the
			# villagers, where the player's first house wants to go.
			var too_near := false
			for centre in data.starts:
				if Vector2(t - centre).length() <= float(keep_out):
					too_near = true
					break
			if too_near:
				continue
			claimed[t] = true
			data.add_entity(&"res.tree", 0, t,
					absi(t.x * 40503 ^ t.y * 12289) % classes)
