## The procedural map generator (PLAN.md 2.4b), ported into the game from the
## `game_map_gen/` prototype 2026-08-17 with the eight changes PLAN.md 11.2 records.
##
## Produces a `MapData` -- terrain plus an entity list -- never a `SimWorld`. See
## `MapData`'s header for why that indirection carries its weight.
##
## **`generate()` VALIDATES AND RETRIES.** A map that leaves a player walled in is
## unplayable and invisible until someone plays it, so the connectivity gate
## (`MapValidator`) is built into the entry point rather than offered beside it. If
## every attempt fails, the last map comes back with `meta.problems` filled in, so a
## caller can refuse to start rather than being handed something broken with no way to
## tell.
##
## ## Two departures from the prototype worth stating plainly
##
## **Size is by AREA, not by side.** The prototype grew the side linearly with player
## count, so 8 players got 8x the side and **64x the area** of 2. A player needs about
## one debug map's worth of room (2.4a calls 64x64 generous for one), so the side is
## `64 * sqrt(players)`: 2P 96, 4P 128, 8P 184. This is the single most consequential
## number here, because **fog of war is one byte per tile per player** -- a 300x300 map
## would put ~90 KB of vision into every snapshot, against the 4 KB measured today.
##
## **The generated map is SENT to joining clients, not regenerated by them.** 2.4a's
## rule was that each client builds its own world from the shared `MatchConfig`, which
## holds for the hand-built debug map because it is integer code. This generator uses
## `FastNoiseLite`, whose float maths is not guaranteed identical between an ARM phone
## and an x86 desktop -- and a host and client that disagree about where the water is
## have desynced before the first order, in the one way `state_hash()` cannot help
## with because it would report the divergence without saying why. A `MapData` is
## ~10-25 KB (`to_dict()`), sent once at match start. Certainty for one small message.
class_name MapGenerator
extends RefCounted

## RANDOM resolves to one of the four at generation time, so the skirmish screen can
## offer it as a choice (1.6) without the caller having to roll it.
enum Type { RANDOM, ISLAND, RIVER, DESERT, FOREST }

const MIN_PLAYERS := 2
const MAX_PLAYERS := 8

## One player's comfortable room, per 2.4a's note on the 64x64 debug map. The side is
## derived from `BASE_SIDE * sqrt(players)` and rounded up to a multiple of
## `SIDE_MULTIPLE`, purely so sizes read as round numbers.
const BASE_SIDE := 64
const SIDE_MULTIPLE := 16

## Ground cleared around a start, BEYOND the town centre's own footprint, on every
## side. A 10x10 town centre therefore gets a 22x22 clearing.
const START_CLEARANCE := 6
## Chebyshev radius from the start centre for the villagers and the scout. The town
## centre's footprint reaches radius 5, so 7 leaves two clear tiles between the wall
## and the nearest unit -- the prototype's radius 4 put every villager INSIDE its own
## town centre.
const UNIT_RING_RADIUS := 7
## How far from the start centre a resource vein begins (the owner's figure).
const VEIN_DISTANCE := 9
## Tiles of each kind to try to place per start.
const STONE_TILES := 35
const GOLD_TILES := 12
## Hard ceiling on a vein's random walk. The prototype had none, and counted only
## pixels it actually wrote -- so a vein that walked off the map wrote nothing, never
## reached its target, and span.
const VEIN_MAX_STEPS := 400

## Trees are placed as COPSES on scattered anchors, not one per tile of a wood region,
## and **the density is a wire-format decision rather than a cosmetic one**: every tree
## is a `SimResourceNode` in `entities`, and the snapshot carries entities.
##
## Two numbers found by looking at the output. A one-per-tile forest put **1472 trees**
## on a 96x96 map and made the map 209 KB to send. Thinning that to a strict lattice
## fixed the count and produced a visible REGULAR GRID of single trees — an orchard,
## and the lattice spacing readable straight off the picture. So: anchors on a coarse
## lattice, each carrying a small jittered clump, which gives the same count grouped
## into woods with clearings between them.
##
## The trade is worth naming: **AoE-style solid forest is not affordable under a
## full-state snapshot** (7.2). A wood here is a handful of rich trees rather than a
## thousand poor ones — `res.tree` carries up to 175 wood a node, so a copse is worth
## walking to. A real delta encoding is what would buy the dense version.
const TREE_CLUMP_SPACING := 8

## One copse, as tile offsets from its anchor. A loose blob about 3x3 rather than a
## solid square, so the sprites overlap into a canopy with gaps of light in it.
const TREE_CLUMP_SHAPE := [
	Vector2i(0, 0), Vector2i(2, 0), Vector2i(1, 2), Vector2i(3, 2), Vector2i(0, 3),
]

## Trees placed around every start regardless of map type, in a loose ring this far out.
##
## **Start resources are PLACED, not sampled.** The first version left them to the
## terrain noise and the validator immediately caught what that costs: a desert start
## had one reachable tree and no food at all. Every real RTS map generator guarantees
## an opening; hoping the noise put a wood nearby is how a player gets a start they
## cannot play.
const START_WOOD_COUNT := 8
const START_WOOD_MIN := 11
const START_WOOD_MAX := 17
const START_FOOD_COUNT := 4

## How many times to regenerate before giving up on validation.
const MAX_ATTEMPTS := 8

## Noise shape per map type. **Tune these by running
## `dev_preview/preview_mapgen.tscn` and looking**, which is the only way to judge
## them -- the numbers say nothing on their own.
##
## `freq` is feature SIZE (lower = bigger, smoother regions) and `wood` is the
## threshold above which a tile may carry trees. The two together set both the look
## and the tree count, and the count is a wire-format cost -- see TREE_CLUMP_SPACING.
##
## **They are two separate knobs, and moving both at once is how this went wrong
## twice.** `freq` is a WAVELENGTH: features come out about `1 / freq` tiles across, so
## it sets the SIZE of a wood. `wood` is a percentile cut on the noise, so it sets what
## FRACTION of the map is wooded — and therefore the tree count, which is a wire cost.
##
## The mistake worth recording, because it is counter-intuitive: chasing "bigger, more
## connected woods" by lowering the frequency to 0.010 made it worse, not better. At
## 0.010 the wavelength is ~100 tiles, which on a 96-tile map is a single gradient
## across the whole thing — so a threshold anywhere near the middle covers most of the
## map fairly evenly and the copses spread out over all of it. **Distinct woods with
## lanes between them need a wavelength a few times SMALLER than the map**, around
## 25-35 tiles, i.e. `freq` about 0.03. Small features with a high threshold (the first
## attempt, 0.018/0.12) gives confetti; large features with any threshold gives a wash;
## the middle gives woods.
const SHAPE := {
	Type.FOREST: {"freq": 0.035, "wood": 0.08, "lake": 0.52},
	Type.RIVER: {"freq": 0.030, "wood": 0.28, "lake": 1.0},
	Type.ISLAND: {"freq": 0.040, "wood": 0.10, "lake": 1.0},
	Type.DESERT: {"freq": 0.030, "wood": 0.05, "lake": 1.0},
}


## Side length in tiles for `players`, by AREA per player. See the class header.
static func side_for(players: int) -> int:
	var count := clampi(players, MIN_PLAYERS, MAX_PLAYERS)
	var ideal := float(BASE_SIDE) * sqrt(float(count))
	return int(ceil(ideal / float(SIDE_MULTIPLE))) * SIDE_MULTIPLE


## A validated map. `meta.problems` is empty on success; if it is not, every attempt
## failed and the caller should refuse to start (1.6 disables Start on it).
static func generate(p_seed: int, type: Type, players: int,
		attempts: int = MAX_ATTEMPTS) -> MapData:
	var count := clampi(players, MIN_PLAYERS, MAX_PLAYERS)
	var last: MapData = null

	for attempt in range(maxi(1, attempts)):
		# A DERIVED seed, not a re-roll: attempt N of seed S is reproducible, so a
		# map that took three tries can still be recovered from the seed the player
		# was shown. Mixed rather than incremented so consecutive seeds do not
		# produce near-identical maps.
		var attempt_seed := p_seed ^ (attempt * 0x9E3779B9)
		last = _generate_once(attempt_seed, type, count)
		var problems := MapValidator.problems(last)
		last.meta["seed"] = p_seed
		last.meta["attempt"] = attempt
		last.meta["problems"] = problems
		if problems.is_empty():
			return last

	return last


static func _generate_once(p_seed: int, type: Type, count: int) -> MapData:
	var rng := RandomNumberGenerator.new()
	rng.seed = p_seed

	var resolved := type
	if resolved == Type.RANDOM:
		resolved = [Type.ISLAND, Type.RIVER, Type.DESERT, Type.FOREST][rng.randi_range(0, 3)]

	var side := side_for(count)
	var data := MapData.create(Vector2i(side, side))

	# 1 where a tree MAY stand. Kept beside the terrain rather than painted into it as
	# `Terrain.FOREST`, because a tree is an entity standing on walkable ground (2.3) --
	# the same arrangement the debug map uses. Chopping a wood then leaves grass
	# behind with nothing to convert.
	var wood := PackedByteArray()
	wood.resize(side * side)

	match resolved:
		Type.ISLAND:
			_paint_island(data, wood, rng)
		Type.RIVER:
			_paint_river(data, wood, rng)
		Type.DESERT:
			_paint_desert(data, wood, rng)
		_:
			_paint_forest(data, wood, rng)

	data.starts = _start_positions(data, resolved, count, rng)

	# Clear every base BEFORE placing anything, so one player's clearing cannot wipe
	# out the town centre of a neighbour whose start landed close by.
	for centre in data.starts:
		_clear_base(data, wood, centre)

	var claimed: Dictionary = {}
	for i in range(count):
		_place_base(data, claimed, i + 1, data.starts[i], resolved, rng)

	_place_trees(data, wood, claimed)

	data.meta["type"] = int(resolved)
	data.meta["players"] = count
	data.meta["format_version"] = MapData.FORMAT_VERSION
	return data


static func type_name(type: Type) -> String:
	match type:
		Type.ISLAND: return "Island"
		Type.RIVER: return "River"
		Type.DESERT: return "Desert"
		Type.FOREST: return "Forest"
		_: return "Random"


# ── terrain ─────────────────────────────────────────────────────────────────

static func _noise(rng: RandomNumberGenerator, frequency: float) -> FastNoiseLite:
	var n := FastNoiseLite.new()
	n.seed = rng.randi()
	n.frequency = frequency
	return n


static func _paint_island(data: MapData, wood: PackedByteArray,
		rng: RandomNumberGenerator) -> void:
	var side := data.size.x
	data.fill_terrain(SimMap.Terrain.WATER_DEEP)
	var centre := Vector2(side, side) * 0.5
	var max_radius := float(side) * 0.44
	var shape := _noise(rng, 0.025)
	var trees := _noise(rng, 0.05)

	for y in range(side):
		for x in range(side):
			var t := Vector2i(x, y)
			var dist := Vector2(x, y).distance_to(centre)
			# Radial mask with a noisy coastline, so the island is round-ish but not
			# a circle.
			var land := (1.0 - dist / max_radius) + shape.get_noise_2d(x, y) * 0.35
			if land <= 0.18:
				# A shallow rim, so the shoreline reads as a beach rather than a cliff
				# into deep water.
				if land > 0.02:
					data.set_terrain(t, SimMap.Terrain.WATER_SHALLOW)
				continue
			data.set_terrain(t, SimMap.Terrain.SAND if land < 0.30 else SimMap.Terrain.GRASS)
			if land > 0.34 and trees.get_noise_2d(x, y) > 0.15:
				wood[data.index_of(t)] = 1


## A CONTINUOUS river with 1-3 NARROW land bridges.
##
## The bridges are the point and they stay (project owner, 2026-08-17). What the
## prototype got wrong was the river: 20-tile bridge gaps in a band left three
## disjoint segments, so it read as three lakes and "players on opposite sides" meant
## nothing. Here the water is unbroken except at the bridges, which are 5 tiles wide.
##
## Sides are decided by the SIGN of the perpendicular distance to the river's centre
## line, so "opposite sides" is a real test rather than an offset that happens to
## work for one direction. The direction itself varies -- the prototype hardcoded the
## `y = x` diagonal.
static func _paint_river(data: MapData, wood: PackedByteArray,
		rng: RandomNumberGenerator) -> void:
	var side := data.size.x
	data.fill_terrain(SimMap.Terrain.GRASS)
	var shape: Dictionary = SHAPE[Type.RIVER]
	var trees := _noise(rng, shape["freq"])
	for y in range(side):
		for x in range(side):
			if trees.get_noise_2d(x, y) > float(shape["wood"]):
				wood[data.index_of(Vector2i(x, y))] = 1

	var axis := _river_axis(rng)
	var half_width: float = maxf(2.5, float(side) * 0.045)
	var bridges := _bridge_positions(side, rng)

	for y in range(side):
		for x in range(side):
			var t := Vector2i(x, y)
			if absf(_river_offset(data, axis, t)) > half_width:
				continue
			var along := _river_along(data, axis, t)
			var on_bridge := false
			for b in bridges:
				if absf(along - b) <= 2.5:          # a 5-tile crossing
					on_bridge = true
					break
			if on_bridge:
				continue
			data.set_terrain(t, SimMap.Terrain.WATER_SHALLOW)
			wood[data.index_of(t)] = 0


static func _paint_desert(data: MapData, wood: PackedByteArray,
		rng: RandomNumberGenerator) -> void:
	var side := data.size.x
	data.fill_terrain(SimMap.Terrain.SAND)
	var oases := _noise(rng, 0.03)
	var scrub := _noise(rng, 0.09)

	for y in range(side):
		for x in range(side):
			var t := Vector2i(x, y)
			var n := oases.get_noise_2d(x, y)
			if n > 0.55:
				data.set_terrain(t, SimMap.Terrain.WATER_SHALLOW)
			elif n > 0.42:
				# A green fringe around each oasis, which is where the little wood a
				# desert has belongs -- the prototype scattered single trees uniformly
				# at random, which reads as noise rather than as an oasis.
				data.set_terrain(t, SimMap.Terrain.GRASS)
				if scrub.get_noise_2d(x, y) > 0.1:
					wood[data.index_of(t)] = 1


static func _paint_forest(data: MapData, wood: PackedByteArray,
		rng: RandomNumberGenerator) -> void:
	var side := data.size.x
	data.fill_terrain(SimMap.Terrain.GRASS)
	var shape: Dictionary = SHAPE[Type.FOREST]
	var canopy := _noise(rng, shape["freq"])
	var lakes := _noise(rng, 0.04)

	for y in range(side):
		for x in range(side):
			var t := Vector2i(x, y)
			if lakes.get_noise_2d(x, y) > float(shape["lake"]):
				data.set_terrain(t, SimMap.Terrain.WATER_SHALLOW)
				continue
			# Broad wood regions with lanes between them, rather than the prototype's
			# copses on grass. See SHAPE for why the frequency is this low.
			if canopy.get_noise_2d(x, y) > float(shape["wood"]):
				wood[data.index_of(t)] = 1


# ── the river's geometry ────────────────────────────────────────────────────

## One of four directions, as (along, perpendicular) integer vectors.
static func _river_axis(rng: RandomNumberGenerator) -> Array:
	match rng.randi_range(0, 3):
		0: return [Vector2(1, 0), Vector2(0, 1)]        # runs east-west
		1: return [Vector2(0, 1), Vector2(1, 0)]        # runs north-south
		2: return [Vector2(1, 1).normalized(), Vector2(1, -1).normalized()]
		_: return [Vector2(1, -1).normalized(), Vector2(1, 1).normalized()]


## Signed perpendicular distance from the river's centre line, in tiles. Its SIGN is
## which bank `t` is on.
static func _river_offset(data: MapData, axis: Array, t: Vector2i) -> float:
	var centre := Vector2(data.size) * 0.5
	return (Vector2(t) - centre).dot(axis[1] as Vector2)


## Distance along the river from its middle, in tiles. Used to place the bridges.
static func _river_along(data: MapData, axis: Array, t: Vector2i) -> float:
	var centre := Vector2(data.size) * 0.5
	return (Vector2(t) - centre).dot(axis[0] as Vector2)


static func _bridge_positions(side: int, rng: RandomNumberGenerator) -> Array[float]:
	var count := rng.randi_range(1, 3)
	var span := float(side) * 0.7          # keep crossings away from the corners
	var out: Array[float] = []
	for i in range(count):
		var fraction := (float(i) + 1.0) / (float(count) + 1.0)
		out.append((fraction - 0.5) * span)
	return out


# ── player starts ───────────────────────────────────────────────────────────

static func _start_positions(data: MapData, type: Type, count: int,
		rng: RandomNumberGenerator) -> Array[Vector2i]:
	if type == Type.RIVER:
		return _river_start_positions(data, count, rng)

	# Equally spread around a ring, with a random rotation so the same player count
	# does not always start in the same corners.
	var side := data.size.x
	var centre := Vector2(side, side) * 0.5
	var radius := float(side) * 0.5 - float(side) * 0.19
	var offset := rng.randf_range(0.0, TAU)
	var out: Array[Vector2i] = []
	for i in range(count):
		var angle := offset + float(i) * TAU / float(count)
		out.append(_clamp_start(data,
				Vector2i(centre + Vector2(cos(angle), sin(angle)) * radius)))
	return out


## Alternating banks, spread along the river's length.
##
## Players alternate sides, so an even count is balanced and an odd one puts the
## extra player on the bank that has fewer -- the owner's rule for 3, 5 and 7.
static func _river_start_positions(data: MapData, count: int,
		rng: RandomNumberGenerator) -> Array[Vector2i]:
	var side := data.size.x
	var centre := Vector2(side, side) * 0.5
	var axis := _river_axis(rng)
	var bank := float(side) * 0.26
	var span := float(side) * 0.55

	# How many land on each bank, so each bank can spread its own players evenly.
	var per_bank := [0, 0]
	for i in range(count):
		per_bank[i % 2] += 1

	var placed := [0, 0]
	var out: Array[Vector2i] = []
	for i in range(count):
		var s := i % 2
		var n: int = per_bank[s]
		var fraction := 0.5 if n == 1 else float(placed[s]) / float(n - 1)
		placed[s] += 1
		var along := (fraction - 0.5) * span
		var side_sign := 1.0 if s == 0 else -1.0
		var pos := centre + (axis[0] as Vector2) * along \
				+ (axis[1] as Vector2) * bank * side_sign
		out.append(_clamp_start(data, Vector2i(pos)))
	return out


## Keep a start far enough inside the map that its clearing and its unit ring fit.
static func _clamp_start(data: MapData, t: Vector2i) -> Vector2i:
	var margin := _base_half_extent() + START_CLEARANCE
	return Vector2i(
			clampi(t.x, margin, data.size.x - 1 - margin),
			clampi(t.y, margin, data.size.y - 1 - margin))


## Half the town centre's footprint, rounded up -- how far its walls reach from the
## start centre. Read from `buildings.json` rather than hardcoded, which is fix (3):
## the prototype reserved 5x5 for a building that is 10x10 in the data.
static func _base_half_extent() -> int:
	var bd: BuildingDef = GameDataRegistry.building(&"building.town_center")
	var footprint := bd.footprint if bd != null else Vector2i(10, 10)
	return int(ceil(float(maxi(footprint.x, footprint.y)) * 0.5))


## Flatten and dry the ground a base needs, and clear the wood off it.
static func _clear_base(data: MapData, wood: PackedByteArray, centre: Vector2i) -> void:
	var reach := _base_half_extent() + START_CLEARANCE
	var ground := data.terrain_at(centre)
	# Keep a desert base on sand and everything else on grass, so a cleared start does
	# not read as a green patch cut out of a desert.
	if ground != SimMap.Terrain.SAND:
		ground = SimMap.Terrain.GRASS
	# ROUNDED, not square. A square clearing draws a hard right-angled patch of grass
	# across a beach or a desert, which reads as a tool mark rather than as a
	# settlement -- visible immediately on the 8-player island preview. The corners are
	# outside the town centre's footprint anyway, so trimming them costs nothing.
	var trim := float(reach) + 1.0
	for y in range(centre.y - reach, centre.y + reach + 1):
		for x in range(centre.x - reach, centre.x + reach + 1):
			var t := Vector2i(x, y)
			var i := data.index_of(t)
			if i < 0:
				continue
			if Vector2(t - centre).length() > trim:
				continue
			data.terrain[i] = ground
			wood[i] = 0


static func _place_base(data: MapData, claimed: Dictionary, player: int,
		centre: Vector2i, type: Type, rng: RandomNumberGenerator) -> void:
	var bd: BuildingDef = GameDataRegistry.building(&"building.town_center")
	var footprint := bd.footprint if bd != null else Vector2i(10, 10)
	var origin := centre - footprint / 2
	data.add_entity(&"building.town_center", player, origin)
	for t in MapData.footprint_rect_of(data.entities[data.entities.size() - 1]):
		claimed[t] = true

	# Villagers and the scout on a ring outside the walls, at every other position so
	# no two stand adjacent. `unit.scout_cavalry` -- fix (4): `unit.scout` does not
	# exist in units.json.
	var ring := _ring_tiles(centre, UNIT_RING_RADIUS)
	var wanted := MapGen.STARTING_VILLAGERS + 1
	var step := maxi(2, ring.size() / maxi(1, wanted))
	var placed := 0
	var i := 0
	while placed < wanted and i < ring.size():
		var t: Vector2i = ring[i]
		i += step
		if not data.is_ground_passable(t) or claimed.has(t):
			continue
		claimed[t] = true
		data.add_entity(&"unit.scout_cavalry" if placed == wanted - 1
				else &"unit.villager", player, t)
		placed += 1

	# The guaranteed opening. Every start gets stone, gold, food and wood within
	# walking distance whatever the terrain did -- see START_WOOD_COUNT's header for
	# what leaving this to the noise cost.
	_place_vein(data, claimed, centre, &"res.stone", STONE_TILES, rng)
	_place_vein(data, claimed, centre, &"res.gold_mine", GOLD_TILES, rng)
	_place_scatter(data, claimed, centre, &"res.berry_bush", START_FOOD_COUNT,
			START_WOOD_MIN, START_WOOD_MAX, rng)
	_place_scatter(data, claimed, centre, &"res.tree", START_WOOD_COUNT,
			START_WOOD_MIN, START_WOOD_MAX, rng)


## Tiles at exactly Chebyshev `radius` from `centre`, clockwise from the north-west
## corner. A fixed order, because two clients placing a start must agree.
static func _ring_tiles(centre: Vector2i, radius: int) -> Array[Vector2i]:
	var out: Array[Vector2i] = []
	for x in range(centre.x - radius, centre.x + radius + 1):
		out.append(Vector2i(x, centre.y - radius))
	for y in range(centre.y - radius + 1, centre.y + radius + 1):
		out.append(Vector2i(centre.x + radius, y))
	for x in range(centre.x + radius - 1, centre.x - radius - 1, -1):
		out.append(Vector2i(x, centre.y + radius))
	for y in range(centre.y + radius - 1, centre.y - radius, -1):
		out.append(Vector2i(centre.x - radius, y))
	return out


## Scatter `count` nodes of `def_id` in a ring between `min_r` and `max_r` tiles of
## `centre`, skipping anything claimed or unwalkable.
##
## Angles are stepped evenly with a random rotation rather than drawn independently,
## so a cluster spreads around the base instead of clumping on one side -- and gives
## up after a bounded number of tries rather than searching forever for room.
static func _place_scatter(data: MapData, claimed: Dictionary, centre: Vector2i,
		def_id: StringName, count: int, min_r: int, max_r: int,
		rng: RandomNumberGenerator) -> void:
	var rd: ResourceDef = GameDataRegistry.resource_def(def_id)
	if rd == null:
		return
	var offset := rng.randf_range(0.0, TAU)
	var placed := 0
	var attempts := 0
	while placed < count and attempts < count * 12:
		# Sweep the ring rather than re-rolling the same angle: `attempts` advances the
		# angle, so a blocked direction is stepped past instead of retried.
		var angle := offset + float(attempts) * TAU / float(maxi(1, count * 3))
		var radius := rng.randf_range(float(min_r), float(max_r))
		attempts += 1
		var tile := centre + Vector2i(Vector2(cos(angle), sin(angle)) * radius)
		var size_class := rng.randi_range(0, maxi(0, rd.amounts.size() - 1))
		var footprint := rd.footprint_for_size(size_class)

		var free := true
		for y in range(tile.y, tile.y + footprint.y):
			for x in range(tile.x, tile.x + footprint.x):
				var t := Vector2i(x, y)
				if claimed.has(t) or not data.is_ground_passable(t):
					free = false
					break
			if not free:
				break
		if not free:
			continue

		data.add_entity(def_id, 0, tile, size_class)
		for t in MapData.footprint_rect_of(data.entities[data.entities.size() - 1]):
			claimed[t] = true
		placed += 1


## Walk a vein of `def_id` outward from `VEIN_DISTANCE` tiles off the base, placing
## nodes until `target_tiles` tiles are claimed or the walk runs out of steps.
##
## The step cap is fix (8): the prototype counted only tiles it actually wrote, so a
## vein that wandered off the map or back over itself never reached its target and
## looped. It also had no guard against drawing over a town centre; `claimed` is that
## guard, and it is shared across every base and vein on the map.
static func _place_vein(data: MapData, claimed: Dictionary, centre: Vector2i,
		def_id: StringName, target_tiles: int, rng: RandomNumberGenerator) -> void:
	var rd: ResourceDef = GameDataRegistry.resource_def(def_id)
	if rd == null:
		return

	var angle := rng.randf_range(0.0, TAU)
	var cursor := centre + Vector2i(Vector2(cos(angle), sin(angle)) * float(VEIN_DISTANCE))
	var drift := Vector2i(rng.randi_range(-1, 1), rng.randi_range(-1, 1))
	if drift == Vector2i.ZERO:
		drift = Vector2i(1, 0)          # a zero drift never moves and never terminates

	var claimed_here := 0
	var steps := 0
	while claimed_here < target_tiles and steps < VEIN_MAX_STEPS:
		steps += 1
		if rng.randf() < 0.25:
			drift = Vector2i(rng.randi_range(-1, 1), rng.randi_range(-1, 1))
			if drift == Vector2i.ZERO:
				drift = Vector2i(0, 1)
		cursor += drift

		var size_class := rng.randi_range(0, maxi(0, rd.amounts.size() - 1))
		var footprint := rd.footprint_for_size(size_class)
		var free := true
		for y in range(cursor.y, cursor.y + footprint.y):
			for x in range(cursor.x, cursor.x + footprint.x):
				var t := Vector2i(x, y)
				if claimed.has(t) or not data.is_ground_passable(t):
					free = false
					break
			if not free:
				break
		if not free:
			continue

		data.add_entity(def_id, 0, cursor, size_class)
		for t in MapData.footprint_rect_of(data.entities[data.entities.size() - 1]):
			claimed[t] = true
			claimed_here += 1


## Copses on anchors over the wood mask, skipping anything already claimed.
##
## Everything random here comes from a HASH OF THE ANCHOR rather than from the rng --
## the jitter, the clump's rotation and each tree's size class. That makes the whole
## wood a pure function of the mask, so it cannot depend on the order tiles are visited
## (PLAN.md 7.1) and a tree keeps its size if this loop is ever reordered. It is also
## what breaks the lattice up: without the jitter the anchors are visibly on a grid.
static func _place_trees(data: MapData, wood: PackedByteArray,
		claimed: Dictionary) -> void:
	var rd: ResourceDef = GameDataRegistry.resource_def(&"res.tree")
	var classes := maxi(1, rd.amounts.size() if rd != null else 1)

	for ay in range(0, data.size.y, TREE_CLUMP_SPACING):
		for ax in range(0, data.size.x, TREE_CLUMP_SPACING):
			var anchor := Vector2i(ax, ay)
			var i := data.index_of(anchor)
			if i < 0 or wood[i] == 0:
				continue

			var h := absi(ax * 73856093 ^ ay * 19349663)
			# Jitter by up to +/-2 tiles, so no two copses sit on the same grid.
			var jittered := anchor + Vector2i(h % 5 - 2, (h / 5) % 5 - 2)
			# Rotate which tiles of the shape are used, so the copses are not clones.
			var rotate := (h / 25) % TREE_CLUMP_SHAPE.size()

			for n in range(TREE_CLUMP_SHAPE.size()):
				var offset: Vector2i = TREE_CLUMP_SHAPE[(n + rotate) % TREE_CLUMP_SHAPE.size()]
				var t: Vector2i = jittered + offset
				var ti := data.index_of(t)
				# Still inside the wood: a clump that straddles a clearing edge stops
				# at it rather than spilling trees onto open ground.
				if ti < 0 or wood[ti] == 0 or claimed.has(t):
					continue
				if not data.is_ground_passable(t):
					continue
				claimed[t] = true
				data.add_entity(&"res.tree", 0, t,
						absi(t.x * 40503 ^ t.y * 12289) % classes)
